### ISSUE TITLE
design doc + prototype for data management system

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#1]
This work is related to microbiomedata/workflow_documentation#5 (design doc / api spec for workflow execution automation) but deserves its own "place" (this issue) to track progress and completion.

- [ ] support demo for microbiomedata/workflow_documentation#5
- [ ] facilitate performance of microbiomedata/nmdc-metadata#309
- [ ] SOP for process of generating and integrating new data objects. (see comment below)

**Comment by dwinston** [comment]
cc @kfagnan @dehays

**Comment by ssarrafan** [comment]
@dwinston I know you're on vacation so I will move this to the June sprint which starts next week.

**Comment by ssarrafan** [comment]
Adding backlog label. Not assigned to a sprint.

**Comment by ssarrafan** [comment]
Discussed with @dwinston on SLACK and adding to July Sprint as the goal is to complete this in July.

**Comment by ssarrafan** [comment]
Moving this back to backlog. @dwinston let me know if it should be moved to October's sprint.

**Comment by dwinston** [comment]
Some concerns related to this issue may remain, but will be re-raised as more-targeted fresh issues.
