### ISSUE TITLE
clarify purpose of nmdc_database.json file in this repo and make it easier to 

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-runtime#10]
I frequently need access to the latest NMDC sample metadata for various purposes - e.g analyze patterns of ENVO usage, GOLD usage, sparsity of mixs variables, etc. We also have various collaborators e.g. ENSURABLE who would like access.

Ultimately this will all be available via API but in the interim it would be great to make all this more transparent

Where should I download data?

 - https://polyneme.nyc3.cdn.digitaloceanspaces.com/nmdc/mongo/export/dwinston_share/biosample_set.json.bz2
 - https://github.com/microbiomedata/nmdc-runtime/blob/main/metadata-translation/src/data/nmdc_database.json.zip? 
 - somewhere else?

It looks like the one in this repo is just test data? I only see 716 gold samples. Whereas the polyneme URL has 32k gold samples.

does the one in this repo serve any purpose? I recommend removing it if it doesn't

there was a ticket somewhere about adding metadata to the database object with provenance about when the ingest was performed, what the version/date of source was etc, can't find it now, but we need this

**Comment by dwinston** [comment]
The one in the repo is a snapshot of "real" output of the GOLD ETL (Bill's pipeline), i.e. the output of the [`nmdc_runtime.solids.jgi.run_etl`](https://github.com/microbiomedata/nmdc-runtime/blob/07b38e7b0088229373c8eeb0ce89561294e15090/nmdc_runtime/solids/jgi.py#L59) solid. However, it does not reflect additions after this step of the database reproduction pipeline, e.g. adding data objects.

I have removed the one in the repo, to avoid confusion.

Yes, ultimately, this will be available in the API. I can prepare a distribution after I have finished the curation/validation pipeline.

It will be available as an API object resource. For example,
https://api.nmdc-runtime-dev.polyneme.xyz/objects/ajrh-6sff-63
is an object resource (see docs at https://api.nmdc-runtime-dev.polyneme.xyz/docs or https://api.nmdc-runtime-dev.polyneme.xyz/redoc) that represents the latest regeneration of the equivalent of the repo's former `metadata-translation/src/data/nmdc_database.json.zip`.

**Comment by dwinston** [comment]
The latest NMDC sample metadata is available as a DRS bundle here:
https://drs.microbiomedata.org/ga4gh/drs/v1/objects/y3ax-8bq3-60
(redirects to https://drs.microbiomedata.org/objects/y3ax-8bq3-60).
The link returns a DRS bundle object, with the 15 collections as contents, each a DRS blob.
For example the study set blob is listed with ID "jh4z-z81d-76", so it is retrievable via
https://drs.microbiomedata.org/ga4gh/drs/v1/objects/jh4z-z81d-76
which lists https://portal.nersc.gov/project/m3408/meta/mongoexports/2021-07/study_set.json.bz2 as the url for an access method.
Documentation on the DRS API here: https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/
@turbomam the above information would be good to put in the nmdc-schema README.

The most recent exports are accessible at https://portal.nersc.gov/project/m3408/meta/mongoexports/2021-07/ , but the DRS indirection allows these links to change in the future, for mirroring via other URLs, etc. So the DRS API links should be the advertised links.
