### ISSUE TITLE
Update nmdc-schema to 2.0.0

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#105]
@dwinston I updated the `nmdc-schema` to 2.0.0.  
Do you want to update or do you want me to do it?

**Comment by dwinston** [comment]
@wdduncan you go ahead. Issue the specialized Makefile target on a branch and start a PR to ensure the tests pass, and then merge if they do.

**Comment by wdduncan** [comment]
@dwinston since I'm not longer involved with NMDC can you show @turbomam and @sujaypatil96 how to do this?

**Comment by dwinston** [comment]
@wdduncan sure thing, professor! 😉

**Comment by dwinston** [comment]
stale. superceded by #164
