### ISSUE TITLE
Enable "one-shot" POST request for submission of NMDC-schema-compliant metadata JSON

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#112]

**Comment by dwinston** [comment]
@corilo you expressed interest in an improved Data Management API, separate from the Search API.

Please review the issues #112 (this issue), #113, and #114, which I've included as part of an [Improved Data Management API milestone](https://github.com/microbiomedata/nmdc-runtime/milestone/16). Are there other issues you would like me to address?

**Comment by elais** [comment]
The interface I have been working with to implement this borrows heavily from the interface used in Cromwell and other workflow managers . We initialize a task by (minimally) sending a list of inputs, outputs, and executors. The json input should look something like this.

```json
{
  "inputs": [{"path": "/path/to/file", "url": "http://enpoint/"}],
  "outputs":[],
  "executors": []
}
```
Inputs must be a path to a file (whether that's a file system or url, it doesn't matter at this stage) and outputs a collection or volume. Executors will be task names as defined in the system. Perhaps later we can talk about options but right now I'm thinking each executor should be run on each input, feeding the executors the full collection of inputs. Once a task or group of tasks are initialized the user will receive a collection of task json objects that contain the task ID and a state.

```json
[{
  "task_id": "some-unique-id"
  "state": "PENDING"
}]
```

We return a 201 for successful task creation, 400 for user error in the request, and 503 if our job runner is taking the piss.

**Comment by dwinston** [comment]
@dehays this is ready to test via https://api.dev.microbiomedata.org/docs#/metadata/submit_json_metadata_json_submit_post

The `run_id` returned is currently just a dagster run id, i.e. it corresponds to
`https://dagit-readonly.nmdc-runtime-dev.polyneme.xyz/instance/runs/{run_id}`

**Comment by dwinston** [comment]
The endpoint creates a DrsObject under the hood, etc.
