### ISSUE TITLE
Add a gff to metadata conversion script to the nmdc-runtime

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-runtime#118]
Details to be added by Elais

**Comment by ssarrafan** [comment]
@elais Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by ssarrafan** [comment]
Moving to July per @elais

**Comment by ssarrafan** [comment]
@elais any updates on this issue?  Can it be closed by tomorrow?

**Comment by elais** [comment]
Yes we can close this issue.

**Comment by ssarrafan** [comment]
> Yes we can close this issue.
> […](#)
> On Jul 28, 2022, 10:31 -0600, ssarrafan ***@***.***>, wrote: @elais any updates on this issue? Can it be closed by tomorrow? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Great! If there's any documentation or other notes we can link to this issue let me know.  Closing this.
