### ISSUE TITLE
Add supplement to author-changesheets.md based on Google Sheet (see body)

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-runtime#127]
from [Changesheets: submit via command line with temp authorization](https://docs.google.com/document/d/1cj0osj4JN-VnAlUMVJ-6kycVzxAwnMo7HaADUCaeUcQ/edit#)

to https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/howto-guides/author-changesheets.md

**Comment by ssarrafan** [comment]
@turbomam moving this to Sept but please let me know if you're not actively working on it for the next 2 weeks

**Comment by ssarrafan** [comment]
Over a year old. No updates. Closing issue. @turbomam let me know if you still want to work on this.
