### ISSUE TITLE
Remove Eric Liskov's SPRUCE samples

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-runtime#128]
Eric Liskov's SPRUCE samples are the PEATcosm ones. See the orange highlighted samples in the attached file. 

- <s> [ ] Sujay to add "delete" option to change sheets commands </s>
- [x] Sujay to make Mongo queries to delete the designated samples. 
[DataPortal_SPRUCE.xlsx](https://github.com/microbiomedata/nmdc-server/files/9113435/DataPortal_SPRUCE.xlsx)

**Comment by sujaypatil96** [comment]
@mslarae13: I've gone ahead and deleted the PEATcosm samples associated with the SPRUCE dataset from the above spreadsheet. I've verified if the record still exists in Mongo via the API after deleting it, also via the API, and it does not, so we should be good.

**Comment by sujaypatil96** [comment]
Thank you to @dwinston for all the changes that enabled this.

**Comment by sujaypatil96** [comment]
@mslarae13 closing this issue since all the SPRUCE samples have been removed from NMDC Mongo.
