### ISSUE TITLE
Design and implement the workflow triggering mechanism in the runtime

### ISSUE THREAD

**Issue by elais** [microbiomedata/nmdc-runtime#132]
We need to create a workflow triggering mechanism using dagster and the runtime api. At a high level this needs to look like the following.

- [ ] #134
- [ ] #135
- [ ] #136
- [ ] Make sure the marks are applied to the whole graph.

This will require a two tier design, one in the API runtime and one tier in dagster. Ideally dagster will speak to MongoDB through the API and keep track of the graph of jobs to be run using its own storage and not speak to the MongoDB directly, though if we need for it to do that we can.

We'll need new tables to achieve this

**Comment by aclum** [comment]
@mbthornton-lbl  please comment if this ticket and the subtasks are still needed. They were written by someone who used to work on the project.
