### ISSUE TITLE
dev onboarding workshop

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#144]
Scheduled for 2pm ET / 11am PT today.

/cc @pkalita-lbl @sujaypatil96 @elais @shreddd @turbomam @Michal-Babins

Goals for participants:
* spin up runtime stack on localhost
* implement tiny addition to codebase, perform tests
* review pull requests

**Comment by turbomam** [comment]
I'm coming. Should I make a calendar entry and invite everyone?

**Comment by turbomam** [comment]
Are there any prerequisites I should set up in advance?

**Comment by dwinston** [comment]
@turbomam You can ensure your local docker setup is sound by cloning the repo and running the tests locally:

```
# check out recent commit where tests should be passing
git checkout 8fe09483f5f74fb34fb86ab8b06d638c9efb5c7d
# builds docker containers and runs them
make up-test
# non-skipped tests should pass
make test
# afterwards
make down-test
```

**Comment by dwinston** [comment]
Recording and transcript of the nmdc-runtime dev onboarding session on 2022-09-22 was emailed to all participants the following day. Will add to NMDC Google Drive when appropriate.

For user-facing documentation on system use, see https://microbiomedata.github.io/nmdc-runtime/
