### ISSUE TITLE
Populate IDs in the runtime

### ISSUE THREAD

**Issue by elais** [microbiomedata/nmdc-runtime#161]
Add examples of which IDs we need, when they need to be defined, and how they will be propagated.

**Comment by scanon** [comment]
Let's use the RQC workflow to identify the various IDs we need to resolve or define.

informed_by: This should reference the omics_processing_activity_id that this will be linked to.  
                        This has to be provided as part of the raw data submission.  So we just need to propagate that along.

part_of:           This would be the root ID (e.g. nmdc:mga0xxx).  I guess we would have to generate this when we get the original 
                         submission.

activity_id:      (proposal) Currently we generate this during the workflow but maybe it would make sense for the runtime to
                         compute this.  See comment below.


This part is still in design but here is what we would need under the current plan.

versioned_id:     This would be combination of the predecessor ID and the version number (see next).  
                            This could potential be the activity_id allowing us to collapse these two into a single ID.

predecessor id:  The ID of the immediate upstream activity.  
                             For rqc this is effectively the same as part_of but of other workflows it would be different.

version number: The version/incremented count of the run of this workflow for this input.
                             Propose that this would not reset if an upstream workflow was updated.

**Comment by elais** [comment]
In what context do these IDs need to be resolved? When submitting an activity set? So new read_QC activity sets should include these ids in their request json, or should these be included as fields in the workflows we store in the runtime?

**Comment by scanon** [comment]
As the runtime is creating the job records that can be claimed, it will need to generate these IDs.

The discussion of the IDs are in this slide deck...

https://docs.google.com/presentation/d/1Kh43lFyHBJX5RiV_dJun3DyjHdUE_Q97rhX2WEZJ9Lw/edit#slide=id.p

**Comment by scanon** [comment]
@elais Can this be closed?

**Comment by ssarrafan** [comment]
Per Elais closing
