### ISSUE TITLE
new process to build components separately

### ISSUE THREAD

**Issue by elais** [microbiomedata/nmdc-runtime#162]
Modules added to the components subdirectory are currently being imported directly to the main nmdc api app. Ideally we want to build, test, and version them separately from the api app to maintain a good separation of concerns. However this presents its own challenges including

1. Setting up the repo to import all components along with api app in the dev environment
2. Aggregating test results for the repo and its different pieces for automated testing.
3. Making sure new updates to components are reflected immediately for testing.
4. Only deploying runtime when its expected components are the right version. 
5. This may be a good use case to try any of the myriad python binary builders.

**Comment by ssarrafan** [comment]
@elais said this is completed so I'm closing.
