### ISSUE TITLE
data_object_set record illegally lacking and `id`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-runtime#165]
The DataObject with `{'md5_checksum': 'f13923611789eb5c21ccd45f9607c656'}` is lacking an `id` field.

It looks like their are other DataObjects whose `id` is just their `md5_checksum` with the "nmdc" prefix:

```json
{
  "description": "Sense RPKM for gold:Gp0208347",
  "url": "https://data.microbiomedata.org/data/nmdc_mta0r607/metat_output/nmdc_mta0r607_sense_out.json",
  "md5_checksum": "c46d12ccd3b0fc0c08e1182c56223c92",
  "file_size_bytes": 249336096,
  "id": "nmdc:c46d12ccd3b0fc0c08e1182c56223c92",
  "name": "gold:Gp0208347_Sense RPKM"
}
```

@dwinston @mslarae13 who else should we get involved?

- determine whether we can permanently repair this one entry according to the "nmdc:" + `md5_checksum` pattern
- figure out how this made it into mongodb in the first place

**Comment by elais** [comment]
Is this in prod or dev?

**Comment by turbomam** [comment]
It's from the 'nmdc' database on localhost:27027 when tunneling like this:

```bash
ssh -i ~/.ssh/nersc -L27027:mongo-loadbalancer.nmdc-runtime-dev.development.svc.spin.nersc.org:27017 \
                mam@dtn02.nersc.gov '/bin/bash -c "while [[ 1 ]]; do echo heartbeat; sleep 300; done"'
```

Is that helpful? I didn't think there were both `prod` and `dev` mongodb instances.

**Comment by elais** [comment]
Donny can confirm but I think there's one mongo instance with dev and prod databases attached. The url you sent looks like it's dev related so I think it's ok for there to be some bad data in it. I'll confirm on Monday unless someone else chimes in who's 100% sure here.

**Comment by elais** [comment]
@dwinston could you weigh in on this?

**Comment by dwinston** [comment]
There is only one remote mongo host instance in active use. Its 'nmdc' database is the production database. Other databases on that instance, for example one that stores records that have been “deleted”, and one used to stage and validate records by some runtime jobs, are not generally accessible. Development is currently done on one’s local machine with a local, dockerized mongo host.

@turbomam I imagine the id-less document got in there through a direct write, as a few people have had admin access.

I suggest we do mark-and-sweep garbage collection of data object records and set aside those that aren’t referenced by any activity record (which obviously includes the id-less record).

ID minting was left to sites during the pilot. So perhaps we can find out who submitted it, and if they have an associated activity to submit for it.

**Comment by dwinston** [comment]
I no longer see any `data_object_set` records lacking an `id`. Closing.
