### ISSUE TITLE
Add GoldClient as a Dagster resource

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-runtime#172]
- [ ] Move [GoldClient](https://github.com/microbiomedata/sample-annotator/blob/52fd450537efa7e8e00c1ff9ba4fc9518baa62e9/sample_annotator/clients/gold_client.py#L57) class from sample-annotator into [resources module](https://github.com/microbiomedata/nmdc-runtime/blob/cd7004a65d24329935fd42b8fb2d211f860a3a39/nmdc_runtime/site/resources.py)
- [ ] We should definitely change the implementation to pick up authorization credentials from environment variables instead of a file
- [ ] The CLI stuff doesn't necessarily need to come along with it
- [ ] Consider renaming the class to make it clear that it's pulling from the GOLD API
- [ ] Add an `@resource`-annotated function which provides a `GoldClient` instance similar to [`runtime_api_site_client_resource`](https://github.com/microbiomedata/nmdc-runtime/blob/cd7004a65d24329935fd42b8fb2d211f860a3a39/nmdc_runtime/site/resources.py#L158)
- [ ] Add a [test](https://docs.dagster.io/concepts/resources#testing-resource-initialization) to verify the resource can be initialized

**Comment by pkalita-lbl** [comment]
cc @dwinston @sujaypatil96 feel free to add anything I missed

**Comment by dwinston** [comment]
looks good. check out e.g. https://github.com/microbiomedata/nmdc-runtime/blob/e856bafe404ee0b5228d86e63cc43af40305c242/nmdc_runtime/site/repository.py#L58 for an example of passing env vars to a dagster resource.

**Comment by pkalita-lbl** [comment]
End of sprint 6 update: I'm just getting started on this, should be able to complete in next sprint.

**Comment by ssarrafan** [comment]
@pkalita-lbl what's the status of this?  I'll move to the next sprint but let me know if you won't be actively working on it please.

**Comment by ssarrafan** [comment]
@pkalita-lbl reported that this is being worked on in a branch currently. Moving to the next sprint.

**Comment by ssarrafan** [comment]
@pkalita-lbl are you still working on this one?

**Comment by pkalita-lbl** [comment]
Yes

**Comment by ssarrafan** [comment]
@pkalita-lbl should this continue to the next sprint?  It doesn't appear to be an active issue?

**Comment by pkalita-lbl** [comment]
Sorry, I've been bad about updating this issue. It keeps hanging around for two reasons:

1. It's a poorly scoped task. I thought it was a small task when I made the issue. Turns out it's much larger than I thought. And there's so much discover-as-you-go-type work involved that it's hard to break it down into small issues.
2. I only have sporadic time to work on it. But I am still working on it and anything that I do is going into this PR: https://github.com/microbiomedata/nmdc-runtime/pull/174

**Comment by ssarrafan** [comment]
Ok thanks @pkalita-lbl 
I'll check the PR next time before I call it inactive :)

**Comment by pkalita-lbl** [comment]
2023-03-10: still in progress

**Comment by elais** [comment]
I'll review it this afternoon

**Comment by pkalita-lbl** [comment]
End of sprint update: code review still in process

**Comment by ssarrafan** [comment]
> End of sprint update: code review still in process

I will move this to the next sprint. Is @elais still reviewing this or is just @dwinston now?

**Comment by pkalita-lbl** [comment]
@dwinston is on the case

**Comment by dwinston** [comment]
Done via https://github.com/microbiomedata/nmdc-runtime/pull/174
