### ISSUE TITLE
api-dev studies and biosamples need new `id`s

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#179]
This issue will be considered closed when all `results.id` values at https://api-dev.microbiomedata.org/studies and https://api-dev.microbiomedata.org/biosamples adhere to `nmdc-schema~=7.1.6` [slot](https://github.com/microbiomedata/nmdc-schema/blob/v7.1.6/src/schema/nmdc.yaml#L587) [specs](https://github.com/microbiomedata/nmdc-schema/blob/v7.1.6/src/schema/nmdc.yaml#L491).

**Comment by dwinston** [comment]
related to #211

**Comment by eecavanna** [comment]
Given that the issue description refers to schema version ~7.1.6, I think this issue is obsolete. @dwinston , will you confirm and then close if true? CC'ing @aclum since I think this is related to Napa Re-ID-ing (which has been completed in production).

**Comment by dwinston** [comment]
thanks @eecavanna. Yes, the Napa Re-ID-ing satisfied this.
