### ISSUE TITLE
need `id_typecode_.*` nmdc-schema settings that cover all active classes

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#180]
This issue can be closed when there is [an `id_typecode_.*` setting (v7.1.6 snapshot)](https://github.com/microbiomedata/nmdc-schema/blob/v7.1.6/src/schema/nmdc.yaml#L102) for every populated metadata class (see e.g. https://api-dev.microbiomedata.org/search), or at least a subsuming setting. Adding `id_typecode_activity` and `id_typecode_data_object` would be a minimal solution.

**Comment by turbomam** [comment]
Thanks. I'll try to get some input in one of my meetings between today and Thursday afternoon. Maybe at some point the stakeholders will say "we don't want to be bothered anymore" and they will trust us to pick the typecodes on our own.

**Comment by dwinston** [comment]
current candidates (in "consensus" column):

class | uses_id | typecode | consensus
-- | -- | -- | --
FieldResearchSite | TRUE | nt | frsite
Site | TRUE | nt | site
ChemicalEntity | TRUE | nt | cheme
DataObject | TRUE | dobj | dobj
GeneProduct | TRUE | nt | gprd
Instrument | TRUE | nt | inst
NamedThing | TRUE | nt | nt
OntologyClass | TRUE | nt | ontc
OrthologyGroup | TRUE | nt | orthg
Pathway | TRUE | nt | path
Person | TRUE | nt | pers
PlannedProcess | TRUE | nt | plprc
Reaction | TRUE | nt | rxn
Study | TRUE | sty | sty
CollectingBiosamplesFromSite | TRUE | nt | clsite
MaterialEntity | TRUE | nt | mate
EnvironmentalMaterialTerm | TRUE | nt | evmatt
MetagenomeAssembly | TRUE | acty | wfmgas
MetatranscriptomeAssembly | TRUE | acty | wfmtas
FunctionalAnnotationTerm | TRUE | nt | fnant
OmicsProcessing | TRUE | omprc | omprc
AnalyticalSample | TRUE | nt | ansm
Biosample | TRUE | bsm | bsm
MaterialSample | TRUE | nt | matsm
Activity | TRUE | acty | act
MetatranscriptomeActivity | TRUE | acty | wfmt
WorkflowExecutionActivity | TRUE | acty | wf
BiosampleProcessing | TRUE | bsmprc | bsmprc
MetagenomeAnnotationActivity | TRUE | acty | wfmgan
MetatranscriptomeAnnotationActivity | TRUE | acty | wfmtan
MagsAnalysisActivity | TRUE | acty | wfmag
MetabolomicsAnalysisActivity | TRUE | acty | wfmb
MetaproteomicsAnalysisActivity | TRUE | acty | wfmp
NomAnalysisActivity | TRUE | acty | wfnom
ReadBasedTaxonomyAnalysisActivity | TRUE | acty | wfrbt
ReadQcAnalysisActivity | TRUE | acty | wfrqc

**Comment by dwinston** [comment]
cf. https://github.com/microbiomedata/nmdc-schema/blob/b25ecd439651fd8c5a61426e41f096b4ccf58331/src/docs/typecode_table.md

**Comment by dwinston** [comment]
status: there is now a covering set (https://github.com/microbiomedata/nmdc-schema/blob/b25ecd439651fd8c5a61426e41f096b4ccf58331/src/schema/nmdc.yaml#L102), but this may be extended using the "consensus" values in the table above, and either way, a versioned release of nmdc-schema must be deployed to close this.

**Comment by dwinston** [comment]
This is now done.
