### ISSUE TITLE
Create an ID generator

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc-runtime#212]
I assume this issue just applies to the IDs for the workflow activities.

The root part of the ID will be minted using the ID minter in the runtime.

The job scheduler/generator will need to also add an iteration number (e.g. like a version but isn't exactly the same as the workflow version).

There is logic for this in the prototype scheduler.  This doesn't call out to the minting API but that should be a simple swap.

See

https://github.com/microbiomedata/nmdc-runtime/blob/scanon/alternate_activity_impl/nmdc_runtime/api/boot/sched.py#L167-L193

**Comment by scanon** [comment]
I consider the prototype done and Elias is working on the version that will go into Dagster.

**Comment by ssarrafan** [comment]
@scanon great, I will close this issue then.  Thanks!

**Comment by elais** [comment]
Elais*
