### ISSUE TITLE
Add hotfix functionality

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#23]
When the data needs to be changed, we need to implement a consistent method to make hotfixes to the data.

cc @cmungall @dehays @dwinston @wdduncan

**Comment by wdduncan** [comment]
After meeting with @dwinston and @dehays, we decided on the attached image as a high level workflow for hotfixes.

![NMDC ETL Workflow Proposal](https://user-images.githubusercontent.com/3186638/128081634-f108b12f-0114-41d7-9b7d-c213de4143cb.png)

**Comment by ssarrafan** [comment]
Added to August sprint and added Large label per Bill's update on the stand-up today.

**Comment by ssarrafan** [comment]
@wdduncan since this is a large issue do you anticipate that it will still be done by the end of August?

**Comment by wdduncan** [comment]
@ssarrafan I am working with @dwinston on this. I think we will be able to finish by the end of August.

**Comment by ssarrafan** [comment]
Moving to Sept sprint per @dwinston

**Comment by cmungall** [comment]
It looks like a lot of progress was made on the data model and serialization format for what we are calling the change sheets, in a google doc. Can than doc be linked here?

**Comment by wdduncan** [comment]
Adding a link to Google doc spec of for the change sheet:  

https://docs.google.com/document/d/1gkz0Rp5vzX5KaOG749YIMmEpTM0ziVRvYQf4ZuYO3Ng/edit

(thanks for suggesting this @cmungall !)

**Comment by wdduncan** [comment]
We need to determine how to add/update properties that are inlined and more than two levels deep. For example, the proposed way to relate a study to its team members:
```
study:
  ....
  slots:
  ...
     - has study role
 
study role:
  is_a: named thing
  aliases: ['credit table', 'associated researchers']
  ...
  slots:
    - applies to person
    - has contributor role
```
If we inline the study roles, the json would like this:
```json
{
  "id": "gold:Gs1234",
   "has study role": [
       {
           "applied to person": {"has raw value": "Jane Doe"},
           "has contributor role": "principal investigator"
        },
       {
           "applied to person": {"has raw value": "John Doe"},
           "has contributor role": "co-investigator"
       }
   ]
}
```
The problem is that it is unclear how to add/update a single study role. For example, suppose want to update Jane Doe's orcid:
|set|id|action|value|
|---|---|---|---|
|study|gold:Gs1234|has_study_role.applies_to_person.orcid| "..."|

How can we determine that it is Jane's orcid that needs to be updated?

One solution (of course) is to not inline the data. E.g.:
```json
{
  "id": "gold:Gs1234",
   "has study role": ["role:1234", "role:4567"]
},
{
  "id": "role:1234",
  "applied to person": {"has raw value": "Jane Doe"},
   "has contributor role": "principal investigator"
},
{
  "id": "role:4567",
   "applied to person": {"has raw value": "John Doe"},
   "has contributor role": "co-investigator"
}
```
Now can use spreadsheet template to update the Jane's orcid like so:
|set|id|action|value|
|---|---|---|---|
|study|role:1234|has_study_role.applies_to_person.orcid| "..."|

Some potential drawbacks to this:
- The user has to be able to find the id of the study role.
- ETL may be more complex.

**Comment by cmungall** [comment]
so I didn't think we were inlining the person. If we can reference person by id (e.g. orcid) then it's simpler

but the general question of how to update the primary key for something needs addressed since that PK will be referenced in multiple places

**Comment by wdduncan** [comment]
@cmungall I changed the example to updating the researcher's role. Thanks for pointing that out :)
Regarding persons: Right now we are inlining person values.

**Comment by dehays** [comment]
Is this blocked on deciding how provenance is maintained?  @cmungall You mentioned in a meeting there was already a place in the schema that change information could be stored.  Could you elaborate?

This issue now blocks all post GOLD ETL metadata updates (study attributes, biosample updates, alternative identifier additions, etc) that were expected to be completed in the next couple weeks.

**Comment by dwinston** [comment]
This is not blocked on how provenance is maintained. @wdduncan and I spoke earlier and have more or less agreed on a data-entry format. He is doing some testing now to ensure the format is parseable as expected so that we don’t need to revise the format.

**Comment by ssarrafan** [comment]
@dwinston and @wdduncan can this issue be closed?

**Comment by wdduncan** [comment]
We have spreadsheets implemented. Although, we still have more work to do (e.g., add functionality for deleting data).    
I think we can close this issue. @dwinston please re-open if you want it to remain open.
