### ISSUE TITLE
web links in documentation no longer work

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#230]
The urls listed in the repo documentation, specifically the block below, no longer work

The NMDC metadata as of 2021-10 is available here:

https://drs.microbiomedata.org/ga4gh/drs/v1/objects/sys086d541

The link returns a [GA4GH DRS API bundle object record](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/#_drs_datatypes), with the NMDC metadata collections (study_set, biosample_set, etc.) as contents, each a DRS API blob object.

For example the blob for the study_set collection export, named "study_set.jsonl.gz", is listed with DRS API ID "sys0xsry70". Thus, it is retrievable via

https://drs.microbiomedata.org/ga4gh/drs/v1/objects/sys0xsry70

The returned blob object record lists https://nmdc-runtime.files.polyneme.xyz/nmdcdb-mongoexport/2021-10-14/study_set.jsonl.gz as the url for an access method.

The 2021-10 exports are currently all accessible at https://nmdc-runtime.files.polyneme.xyz/nmdcdb-mongoexport/2021-10-14/${COLLECTION_NAME}.jsonl.gz, but the DRS API indirection allows these links to change in the future, for mirroring via other URLs, etc. So, the DRS API links should be the links you share.

**Comment by dwinston** [comment]
drs.microbiomedata.org needs
- IN PROGRESS repointing to current api.microbiomedata.org load balancer
    - request made to iprequest.lbl.gov
- TODO ssl cert request (see https://github.com/microbiomedata/infra-admin/tree/main/ssl-certs)
    - current cert expired
- TODO install cert and key on Rancher

**Comment by dwinston** [comment]
okay, these work now. would be good to cut an updated export...
