### ISSUE TITLE
Increase size of file transfer over dev API network

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-runtime#231]
The runtime development API found here: https://api-dev.microbiomedata.org/docs#/ has certain endpoints like the `json:submit` endpoint, found here: https://api-dev.microbiomedata.org/docs#/metadata/submit_json_metadata_json_submit_post, which allows users to submit schema compliant JSON data to the Mongo database.

It turns out there is a limit to the size of the files that can be transferred over the network using that endpoint, which is currently 1 MB. We will have files larger than 1 MB for some datasets and would like to be able to submit those as well.

**Comment by shreddd** [comment]
Changed `nginx.ingress.kubernetes.io/proxy-body-size` annotation in Spin to 8m (which is what is on production).

**Comment by ssarrafan** [comment]
@aclum is this still a blocker?

**Comment by aclum** [comment]
No, this was resolved as far as I'm aware.
