### ISSUE TITLE
Issue in `construct_jobs()` on runtime

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-runtime#232]
We are running into an error on the dagster op method called [construct_jobs()](https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/site/ops.py#L308) while trying to ingest JSON data using the `json:submit` endpoint.

CC: @elais

**Comment by aclum** [comment]
@aclum @ssarrafan

**Comment by aclum** [comment]
@elais please close if this is resolved. I assume it is since we are able to submit to the API.

**Comment by ssarrafan** [comment]
@elais can you confirm that this is done and close this issue please

**Comment by ssarrafan** [comment]
@elais said this can be closed. I think he's having internet issues so I'll close it.
