### ISSUE TITLE
Implement NMDC ID generation service

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-runtime#24]
Implement ID generation service for NMDC based on July discussions and approved approach documented in https://docs.google.com/document/d/1cqTKtHTtKfXmfed41FpQGLO-PkXvgYT7_secbu8ZT0w/edit#heading=h.978dcrst4ubh

**Comment by dwinston** [comment]
planning to borrow heavily from the n2t.net/eggnog API: <https://n2t.net/e/n2t_apidoc.html>.

will likely purge and repurpose current [nmdc_runtime.api.endpoints.ids](https://github.com/microbiomedata/nmdc-runtime/blob/e1abea0ae4caf25377b0689d6ee5ba2e4f6ac89f/nmdc_runtime/api/endpoints/ids.py) module.

outline of proposed endoints:
- POST /ids/mint
- POST /ids/bindings
- GET /ids/bindings/{rest:path} (where `rest` is ID plus optional attribute to narrow request)

**Comment by ssarrafan** [comment]
Moved to 'in progress' since Donny is actively working on this.

**Comment by dwinston** [comment]
This is done, housed in the [nmdc_runtime.api.endpoints.ids](https://github.com/microbiomedata/nmdc-runtime/blob/f9a6e6a4b3025048014afaa27f62efa48c00ca36/nmdc_runtime/api/endpoints/ids.py) module, and currently deployed at <https://api.dev.microbiomedata.org/docs> for feedback. Any follow-on work will be raised as new issues.
