### ISSUE TITLE
API endpoint for returning data object records needed for IMG import

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#246]
For a given study_set id, omics_processing_set id, biosample_set id, [WorkflowExecutionActivity](https://w3id.org/nmdc/WorkflowExecutionActivity) id, or data_object_set_id return all parent and children records.

Example use case: for nmdc study_set id  X return all data_object_set records listed as has_output for workflow execution activities metagenome_annotation_activity_set and metagenome_assembly_set

Success criteria: A single API endpoint can be used to find NMDC file download paths for import into JGI's IMG. Required files come from a combination of the metagenome_annotation_activity_set and metagenome_assembly_set. study_set,omics_processing_set, and biosample_set metadata are required to populate JGI's GOLD records.

@mhuntemann @shreddd

**Comment by PeopleMakeCulture** [comment]
Merged into #355
