### ISSUE TITLE
Update workflow automation to use Perlmutter

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#248]
Cori is going away at the end of May, we need the following for the sequencing workflows
- [x] updated to have HTCondor submit to Perlmutter's CPU partition instead of Cori
- [x] evaluate if other updates are needed to support job packing on perlmutter
- [x] evaluate if changes are needed to the default number of restarts to deal with perlmutter instability

Target completion date: June 2

**Comment by scanon** [comment]
We have done a end to end run with one data set and shared/packing was on and worked.  The retries I believe will be okay as is but we can easily adjust it later if we decide it needs to be bumped up.  Additionally we will can add some tools to resubmit a job manually.
