### ISSUE TITLE
Develop code to ingest NEON metadata from NEON 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#249]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 1

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @sujaypatil96 
- Consulted: @aclum @turbomam 
- Informed: @mslarae13 @turbomam 

**Describe the the task?**
- [x] Create code that generates json records for biosamples through omics processing which can be use to submit records to mongo. This should include the following use cases
- sequencing data was generated at Battelle/Argonne (DP1.10086.001 and DP1.10107.001) and is not In GOLD ex BART_001-O-20170612-COMP-DNA1 n=~800 procsm)
- sequencing data was generate at Battelle/Argonne (DP1.10086.001 and DP1.10107.001) and is also in GOLD ex ABBY_062-M-20170606-COMP-DNA1 (n=~492 procsm)
- DP1.10086.001 from NEON, sequencing data from GOLD/JGI ex TEAK_004-O-20210726-comp-DNA1 n=86 procsm

acronyms 
DP1.10086.001 = [Soil physical and chemical properties, periodic](https://data.neonscience.org/data-products/DP1.10086.001)
DP1.10107.001 = Soil microbe metagenome sequences
procsm = samples from NMDC class [ProcessedSample](https://microbiomedata.github.io/nmdc-schema/ProcessedSample/)

NEON `dnaSampleID` will map to an nmdc slot `name` for Class `ProcessedSample`

**Criteria for completion**
- sample json for that contains records for the following soil dnaSampleIDs BART_001-O-20170612-COMP-DNA1, ABBY_062-M-20170606-COMP-DNA1, TEAK_004-O-20210726-comp-DNA1

**Estimate people time**

**Completion Date (Goal)**
- June 16

**Target Sprint Start & End Dates**
- Start: June 5
- End: June 16

**Tag Blocker/Contingent upon issues**
https://github.com/microbiomedata/issues/issues/262
released version of the schema, subtask of https://github.com/microbiomedata/issues/issues/261

**Comment by ssarrafan** [comment]
Still blocked by schema version release.
Timelines/dates need to be updated.
Moving to next sprint as it needs to get done.

**Comment by ssarrafan** [comment]
@sujaypatil96 Is this complete now?  Can this issue be closed? Or do you need one more sprint?

**Comment by sujaypatil96** [comment]
@ssarrafan there are couple of blockers from NEON's end so this needs to run for another sprint.

**Comment by ssarrafan** [comment]
@sujaypatil96 @aclum what's the status of this issue?

**Comment by aclum** [comment]
we have code for sequencing data was generated at Battelle/Argonne (DP1.10086.001 and DP1.10107.001) but still need to work on code for the second two components, 
sequencing data was generate at Battelle/Argonne (DP1.10086.001 and DP1.10107.001) and is also in GOLD  
DP1.10086.001 from NEON, sequencing data from GOLD/JGI 

high priority for the next sprint.

**Comment by ssarrafan** [comment]
I think this issue can be closed but @sujaypatil96 is at a conference so I'll move to the next sprint for closing.  @aclum

**Comment by ssarrafan** [comment]
@sujaypatil96 what's the status of this issue? Can you close it?

**Comment by ssarrafan** [comment]
Ok I'll move to the next sprint in the review column.

**Comment by ssarrafan** [comment]
@dwinston @mbthornton-lbl can you review this early next week so we can close this issue out.  
See related PR: https://github.com/microbiomedata/nmdc-runtime/pull/251

**Comment by mbthornton-lbl** [comment]
_Criteria for completion

    sample json for that contains records for the following soil dnaSampleIDs BART_001-O-20170612-COMP-DNA1, ABBY_062-M-20170606-COMP-DNA1, TEAK_004-O-20210726-comp-DNA1_

#251 has the ability to output a .json of the ingested NEON data ( I think - @sujaypatil96 can you confirm?) 

If we add the above dnaSampleIDs to the acceptance criteria for #251 we should be able to close this ticket as a duplicate
