### ISSUE TITLE
Timestamp format validates with json:validate but fails at perform mongo updates

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#252]
I thought we had a ticket for this since it was also an issue for GSP but I couldn't find it. The following validates with json:validate but fails with json:submit

```json
"nom_analysis_activity_set": [
    {
      "id": "nmdc:wfnom-11-wmhnby59",
      "started_at_time": "2023-05-30T13:57:34",
      "ended_at_time": "2023-05-30T13:57:34",
      "was_informed_by": "nmdc:omprc-11-2mqs2v64",
      "used": "12T_FTICR_B",
      "execution_resource": "EMSL-RZR",
      "git_url": "https://github.com/microbiomedata/enviroMS",
      "has_input": [
        "nmdc:dobj-11-qyxqsn20"
      ],
      "has_output": [
        "nmdc:dobj-11-jm3anz62"
      ],
      "type": "nmdc:NomAnalysisActivity",
      "has_calibration": "False"
    }
 ]

```

dgaster failure ad perform_mongo_update

dagster._core.definitions.events.Failure: data.nom_analysis_activity_set[0].ended_at_time must be date-time

https://dagit.nmdc-dev.development.svc.spin.nersc.org/runs/7954038a-8c3f-421f-8a2e-7e2a6d0fdbfc?focusedTime=1685574408528&logFileKey=dvrirupc

The same validation should be used by json:validate and json:submit.

cc @turbomam @shreddd

**Comment by dwinston** [comment]
not deployed yet. will close when deployed to prod.

**Comment by dwinston** [comment]
deployed
