### ISSUE TITLE
support sequencing automation when reads are not interleaved

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#257]
The sequencing data from NEON will come not interleaved. An omics_processing_set record will have listed in [has_output](https://microbiomedata.github.io/nmdc-schema/has_output/) 2 data_object_set ids. Those ids will correspond to read 1 (slot [data_object_type](https://microbiomedata.github.io/nmdc-schema/data_object_type/) will be populated with FileTypeEnum Metagenome Raw Read 1) and read 2 (slot [data_object_type](https://microbiomedata.github.io/nmdc-schema/data_object_type/) will be populated with FileTypeEnum Metagenome Raw Read 2).

Per Shane runtime automation only accepts interleaved data currently so needs to be updated to be able to handle the input raw data not being interleaved.

**Comment by Michal-Babins** [comment]
The plan right now is to make an intermediate process that will create a sequencing activity record that will reflect the sequencing data object as an interleaved fastq.

**Comment by ssarrafan** [comment]
@aclum @Michal-Babins Is this still a priority? Should this be in the next sprint?

**Comment by Michal-Babins** [comment]
Hey @ssarrafan, this is currently in review by me and @scanon
