### ISSUE TITLE
slot 'name' for Class DataObject should be populated with the data object's name

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#261]
We have some records from workflow execution activity records that populate slot `name` with descriptions instead of the file name. 

Tasks 
- [ ] The runtime automation code that generates the data object json for sequencing execution activity records should be updated to use the file name instead of a description. 
- [ ] existing records in mongo prod should be cleaned up.

example record 
{
    "_id" : ObjectId("63ffbec2434ebba66bf16aee"),
    "description" : "Structural annotation GFF file for gold:Gp0324006",
    "url" : "https://data.microbiomedata.org/data/503568_190750/annotation/503568_190750_structural_annotation.gff",
    "md5_checksum" : "b47043e6401a909c5c162523012c5df4",
    "file_size_bytes" : NumberInt(28512891),
    "id" : "nmdc:b47043e6401a909c5c162523012c5df4",
    "name" : "gold:Gp0324006_Structural annotation GFF file",
    "data_object_type" : "Structural Annotation GFF",
    "type" : "nmdc:DataObject"
}

Here `name` should be updated to the suffix of `url`, 503568_190750_structural_annotation.gff

Target completion date for updating runtime automation is July 7th

cc @scanon @hubin-keio

**Comment by Michal-Babins** [comment]
This should be updated in the code, but will not be able to test until the scheduler is redoployed against the dev instance with new versions

**Comment by ssarrafan** [comment]
@Michal-Babins @aclum I'm moving to the next sprint to complete the testing per July 7th target.

**Comment by Michal-Babins** [comment]
This has been updated to reflect in the automation code to switch out the name slot with file_name value.

**Comment by aclum** [comment]
@ssarrafan would you spin the data cleanup to a separate ticket. That is still outstanding.

**Comment by ssarrafan** [comment]
> 

For the next sprint? Or backlog?

**Comment by aclum** [comment]
backlog please @ssarrafan
