### ISSUE TITLE
Dagster sensors are all OFF in new development environment

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#271]
a changesheets submission to dev earlier today did not go through. Upon checking, all of the sensors are turned off in development. `apply_changesheets` is the job that does this. Comparing dev to prod, all sensors are off in dev

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/ae3a7ae7-f07c-4ac8-aaa4-e98dff0d5307)

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/1d926d35-0aa0-401c-b4bb-c4f15d06deec)

**Comment by dwinston** [comment]
I've manually activated the `claim_and_run_apply_changesheet_jobs`, `claim_and_run_metadata_in_jobs`, and `process_workflow_job_triggers` sensors.

I plan to close this issue once I open a new issue (referencing this one) to ensure desired sensor toggling on startup of new runtime deployments so that we don't encounter this issue again.

**Comment by ssarrafan** [comment]
@dwinston did you open the new issue referencing this one?  Can this issue be closed?

**Comment by eecavanna** [comment]
Here's a follow-up screenshots showing the current state of the sensors.

![Image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/35571ef5-7183-4489-a634-8a7fa0b17233)

**Comment by eecavanna** [comment]
Hi @dwinston,

> to ensure desired sensor toggling on startup of new runtime deployments

I found a comment on GitHub referring to a parameter to the `@sensor` decorator, called `default_status`, which can be assigned the value `DefaultScheduleStatus.RUNNING`. Link to comment: https://github.com/dagster-io/dagster/issues/4103#issuecomment-1043520688

Here's a link to the documentation about the `default_status` parameter:
- https://docs.dagster.io/_apidocs/schedules-sensors#dagster.sensor

Here's a link to an example of that parameter being set to `DefaultSensorStatus.RUNNING)`:
- https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors#defining-a-sensor

I think adding that parameter to the `@sensor` decorations in `nmdc_runtime/site/repository.py` would make it so those sensors start out as running when Dagster gets deployed.

**Comment by dwinston** [comment]
@eecavanna fantastic! let's do that. would you like to draft a PR?

**Comment by eecavanna** [comment]
@dwinston, sure! I'll open one this afternoon. I don't have my local environment set up for testing the changes locally yet, but I will at least put the changes in a PR this afternoon.

**Comment by ssarrafan** [comment]
Per messages above I'll close this one. Thank you for the updates @dwinston @eecavanna
