### ISSUE TITLE
changesheet issue when a single changesheet has both study_image and has_credit_associations

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#272]
I had an issue when submitting a changesheet where when I used 0 as an index for study_image and has_credit_associations I got a validation error because it tried to has_credit_associations within study_image, see changesheets_validate response document below. To resolve this I had to give study_image an index of 4
Should the following work?

nmdc:sty-11-pzmd0x14 | update | has_credit_associations | 0
0 | update | applies_to_person.name | Alicia Clum
nmdc:sty-11-pzmd0x14 | update | study_image | 0
0 | update | url | https://my_awesome/path/my_awesome_study_image.jpg

response body 
{
  "detail": {
    "update_cmd": {
      "nmdc:sty-11-pzmd0x14": {
        "update": "study_set",
        "updates": [
          {
            "q": {
              "id": "nmdc:sty-11-pzmd0x14"
            },
            "u": {
              "$set": {
                "study_image": [
                  {
                    "applies_to_person": {
                      "name": "Alicia Clum"
                    },
                    "url": "https://my_awesome/path/my_awesome_study_image.jpg"
                  }
                ]
              }
            }
          }
        ]
      }
    },
    "validation_errors": [
      [
        "Additional properties are not allowed ('applies_to_person' was unexpected)"
      ]
    ]
  }
}

**Comment by dwinston** [comment]
No, the following should *not* work:

|id|action|attribute|value|
|-|-|-|-|
nmdc:sty-11-pzmd0x14 | update | has_credit_associations | 0
0 | update | applies_to_person.name | Alicia Clum
nmdc:sty-11-pzmd0x14 | update | study_image | 0
0 | update | url | https://my_awesome/path/my_awesome_study_image.jpg

The credit-association entity and the study-image entity are different entities, and so they should be denoted with different variable names. Perhaps unfortunately, anything without a `:` is currently interpreted as a variable name, including `0`. The `0` does not in this case reference a numerical index into an array, but rather an entity labeled as `0`.
