### ISSUE TITLE
clean up existing data object records from sequencing workflows

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-runtime#273]
This issue is to clean up existing records in mongo prod for data objects. Data objects which have a 'name' that isn't the file name should be updated to the file name.
See related issue at https://github.com/microbiomedata/nmdc-runtime/issues/261 

example record
{
"_id" : ObjectId("63ffbec2434ebba66bf16aee"),
"description" : "Structural annotation GFF file for gold:Gp0324006",
"url" : "https://data.microbiomedata.org/data/503568_190750/annotation/503568_190750_structural_annotation.gff",
"md5_checksum" : "b47043e6401a909c5c162523012c5df4",
"file_size_bytes" : NumberInt(28512891),
"id" : "nmdc:b47043e6401a909c5c162523012c5df4",
"name" : "gold:Gp0324006_Structural annotation GFF file",
"data_object_type" : "Structural Annotation GFF",
"type" : "nmdc:DataObject"
}

Here name should be updated to the suffix of url, 503568_190750_structural_annotation.gff
Issue requested by Alicia

**Comment by dwinston** [comment]
@aclum Is this still desired? Here is a mongo aggregation pipeline to implement:
```
db.data_object_set.aggregate([
  {$match: {url: {$exists: true}},
  {$project: {name: {$last: {$split: ["$url", "/"]}}}},
  {$merge: {into: "data_object_set"}},
]);

**Comment by aclum** [comment]
@dwinston Can you provide a list of what records would change, like what happens w/changesheets before we apply this?

**Comment by dwinston** [comment]
Sure. It looks like 47,369 of 98,336 records (48%) would change. Here are the changes in the form of a changesheet: <https://files.polyneme.xyz/aggregation_query-1692807279.csv>. Although on inspection, it seems a number of the records have a stray space at the end of the `url` field (e.g. https://api.microbiomedata.org/nmdcschema/data_object_set/nmdc:1599297c0a3e797f3b8b97ba9ebe6893), so they are "changed", but really we should strip off the extra space from the `url`s first. Might be good to communicate this upstream / change the schema to constrain the `url` field more than it is currently.

**Comment by PeopleMakeCulture** [comment]
@aclum Is any further work required on this issue? If not can this issue be closed out?

**Comment by aclum** [comment]
Im waiting until after the re-iding process is complete. That should fix many of the data objects and then I'd like to take another pass at malformed data object records. Please leave as backlogged.

**Comment by ssarrafan** [comment]
Closing, this will be resolved through re-iding. @aclum
