### ISSUE TITLE
For NEON ingest code handle cases where platform is in instrument_model

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#279]
relates to https://github.com/microbiomedata/nmdc-runtime/issues/249
For some of the records the ingest code populated `instrument_name` with `Illumina Illumina HiSeq`. This is because some of the NEON records have just platform and some have platform + model in field instrument_model. In those cases our ingest code should just use field instrument_model and not a concatenation of sequencingMethod and instrument_model.
example record

            "id": "nmdc:omprc-11-h5e2px89",
            "instrument_name": "Illumina Illumina HiSeq",
            "name": "Terrestrial soil microbial communities - CPER_002-M-20130701-COMP-DNA1",

**Comment by aclum** [comment]
@sujaypatil96  FYI  i updated the existing records manually w/changesheets in dev and prod today.

**Comment by ssarrafan** [comment]
@sujaypatil96 what's the status of this issue?  
@aclum

**Comment by ssarrafan** [comment]
Doesn't appear to be active. Adding backlog label. @sujaypatil96 @aclum

**Comment by aclum** [comment]
It would be good to get this addressed before the surface water and benthic ingest

**Comment by aclum** [comment]
Closing this a cancelled, in berkeley schema this is modeled differently.
