### ISSUE TITLE
Generate error reports for NMDC ETL staging

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#28]
Part of larger issue #23 

After data is loaded into the NMDC ETL staging database, we need to validate it against the JSON schema and return/out violations. These violations can then be addressed by the hotfixes.

cc @dwinston

**Comment by ssarrafan** [comment]
@wdduncan is it ok to move this to the backlog?  or should it be moved to September's sprint?

**Comment by wdduncan** [comment]
@ssarrafan   
Yes. Donny and I were working on this today, and are going to work on it some more tomorrow. We will finish this in the next sprint.

**Comment by cmungall** [comment]
I think this is high priority

**Comment by ssarrafan** [comment]
@dwinston and @wdduncan can this issue be closed?  I am assuming it's done but please confirm.

**Comment by dwinston** [comment]
Yes, this can be closed.
