### ISSUE TITLE
integrate the various data migration components we are working on

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-runtime#285]
@brynnz22 @Shalsh23 @eecavanna @dwinston @shreddd 

Especially focusing on migration scripts that are released under nmdc-schema vX and migrate from vX-1 to vX

Using a framework like the one @eecavanna has built

**Comment by dwinston** [comment]
can folks note here the components they're working on, with pointers to current state?

**Comment by dwinston** [comment]
note: @eecavanna has submitted a squad proposal to organize this effort

**Comment by eecavanna** [comment]
I consider this issue resolved. 

The pieces are:
- Python notebooks in `nmdc-runtime`
- Migrator classes in `nmdc-schema`

The Python notebook imports the relevant migrator class from the `nmdc-schema` package (published on PyPI) and runs the relevant Mongo data through its methods, which transform that data from (a) adhering to the initial schema version to (b) adhering to the final schema version.

All of this will be documented as part of https://github.com/microbiomedata/nmdc-runtime/issues/304.
