### ISSUE TITLE
Add Projection to the GET /studies endpoint

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-runtime#293]
Would it be possible to add the projection parameter to the [GET /studies endpoint](https://api.microbiomedata.org/docs#/find/find_studies_studies_get)? I am hoping to provide an example in the user api gui documentation of how to retrieve just the dois for a particular study.

**Comment by dwinston** [comment]
sure. this is included in #294. I called it `fields` for the `find` endpoint suite, since it needn't be consistent with MongoDB terminology like for the "metadata" endpoint suite.

**Comment by brynnz22** [comment]
Thanks!
