### ISSUE TITLE
Define and document a `MAJOR.MINOR.PATCH` version identifier for each release

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#302]
I think having a version identifier will allow people to more easily refer to a given "state" of the repository. Currently, I think the closest thing this repository has to a version identifier is the Git commit hash.

There are some [Tags](https://github.com/microbiomedata/nmdc-runtime/tags) in this repository that have names like `v0.1.0` and `v0.1.6`. The latest of those was created in 2022 and refers to commit https://github.com/microbiomedata/nmdc-runtime/commit/b98ca34ec8b3c3a914bc77b89cf72176b8fc082e. There are no [Releases](https://github.com/microbiomedata/nmdc-runtime/releases) in this repository.

Given that merging into `main` causes a deployment to occur, I propose:
- Put a file in the repo that contains the current version identifier (maybe there's a place for it in an existing file); and implement an API endpoint that can be used to fetch that version identifier; and add the version identifier to the top of the Swagger UI page (I think the Swagger UI configuration has a spot for this)
- Tag each merge into `main` (either tag the merge commit, or the commit in which the aforementioned file gets updated); and use the version identifier as the tag name
- Create a Release for each merge into `main`; and use the version identifier as the Release name
- Accompany each Release with release notes (target audience: people that develop parts of the NMDC system)

**Comment by eecavanna** [comment]
> and add the version identifier to the top of the Swagger UI page (I think the Swagger UI configuration has a spot for this)

Here's a screenshot showing the indicator that I had in mind.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/c9e29d8d-dca8-47e3-a275-7b471f052519)

I think developers can control that by using the `version` argument to the `FastAPI` constructor; as in:

https://github.com/microbiomedata/nmdc-runtime/blob/55ceac8417f3c1e186a9acab899eaddfc4f03e03/nmdc_runtime/api/main.py#L340-L344

**Comment by eecavanna** [comment]
Here's a GitHub Action thingy that will automatically update a version number, create a tag, and create a release, depending on what was computer and to which branch.

https://github.com/marketplace/actions/github-tag-and-version-bump

Something like this could facilitate managing a version identifier.

**Comment by eecavanna** [comment]
I think, if we were to switch to using Poetry for dependency management (a separate topic), we could store this project's version identifier in a `project.toml` file, as documented here: https://python-poetry.org/docs/pyproject/#version

**Comment by aclum** [comment]
I have a strong preference for moving us to container images, fine if poetry is used in there but only using poetry means everyone has to install the dependency stack themselves.

**Comment by eecavanna** [comment]
Hi @aclum, I think we are in agreement with each other.

`nmdc-runtime` is already container-ized and I don't want to change that.

When I wrote "dependency management" above, I was referring to managing Python dependencies _within_ a Docker image/container. To rephrase my comment:
> I think, if we were to switch **from using [pip](https://github.com/microbiomedata/nmdc-runtime/blob/712505ed77ef5912c609a02a65944e1bfb3a23a6/nmdc_runtime/fastapi.Dockerfile#L27)** to using Poetry for dependency management (a separate topic) **within the Docker image/container**, [...]

**Comment by dwinston** [comment]
Noting here that each deployed image is tagged with the repo git hash: https://hub.docker.com/repository/docker/microbiomedata/nmdc-runtime-fastapi/general

**Comment by dwinston** [comment]
I agree to "Define and document a MAJOR.MINOR.PATCH version identifier for each release". I am less sure about the proposed strategy. Setting up a GH action seems great, but it isn't obvious that https://github.com/marketplace/actions/github-tag-and-version-bump in particular is widely used (star count) or reliable/up-to-date (trails its upstream by many commits). So I'd want to examine the GH action logic and perhaps simplify/adapt it for our use.

**Comment by eecavanna** [comment]
Thanks for looking into that GitHub Action. I'm OK with us not using any GH Action for this in the short term. I could see it being a distraction/unnecessary complication (and potential risk).

Regarding the Git hash with which the container image is already being tagged, is there any way to view that (or any other version identifier for the runtime) from the API or Swagger UI page?

For example, if a team member encountered and wanted to report an issue with the runtime, I want them to be able to say which version of the runtime they were using (under normal circumstances, they could check the tip of the `main` branch on GitHub, but that might not be accurate when the "redeploy the Spin deployments" is temporarily disabled).

**Comment by eecavanna** [comment]
Hackathon participants: @pkalita-lbl , @dwinston , @PeopleMakeCulture , @eecavanna 

### Accomplishments

- We configured `setup.py` so it generates a version number based upon the latest Git tag
- We configured FastAPI so that Swagger UI shows the current version number at the top of the web page
- We also created a `/version` endpoint to enable programmatic access to version information. It response with: 
    - `nmdc-runtime` version identifier
    - `nmdc-schema` version identifier
    - `fastapi` version identifier
- We created a GitHub Actions workflow that builds the `nmdc-runtime` package and publishes it to PyPI

### Still to do (at least these things)

- Update the container image tag (that ends up on DockerHub) to reflect the new version number. It currently gets tagged with a commit hash instead.

### Other notes

Here's a Mermaid diagram we drew (warning: this was a conversation starter and is not necessarily how things work today):

```mermaid
sequenceDiagram
    actor Developer
    participant GitHub
    participant GHA as GitHub Actions
    participant PyPI
    participant DockerHub
    participant Spin

    Developer ->> GitHub: Create Release x.y.z<br>(and Tag x.y.z)
    GitHub ->> GHA: Trigger workflows
    GHA ->> PyPI: Build and<br>Deploy package x.y.z
    GHA ->> DockerHub: Build and<br>Deploy container image x.y.z
    GHA ->> Spin: Redeploy "deployment" so it pulls latest container image
    Spin -->> DockerHub: Pull latest container image
```

Some notes preserved from the Zoom chat:
- GitHub Releases: https://github.com/microbiomedata/nmdc-runtime/releases
- DockerHub page: https://hub.docker.com/repository/docker/microbiomedata/nmdc-runtime-fastapi/general
- `docker-build.sh`: https://github.com/microbiomedata/nmdc-runtime/blob/main/docker-build.sh
- PyPI page: https://pypi.org/project/nmdc-runtime/

**Comment by eecavanna** [comment]
I plan to close this issue and create a new one focused on the remaining steps. That new issue would reference this issue, but not directly contain all of the brainstorming this one contains (now that we have accomplished what we did during the hackathon).

**Comment by eecavanna** [comment]
I created the following issue about synchronizing the container image tags (which appear on DockerHub) with the version identifiers on GitHub and PyPI.

https://github.com/microbiomedata/nmdc-runtime/issues/359

**Comment by eecavanna** [comment]
An issue has already been created about the other "to do" item from our hackathon session, which was to document the release process and its implications.

https://github.com/microbiomedata/infra-admin/issues/19

I'll close this issue (which was specific to giving `nmdc-runtime` "releases," version numbers).
