### ISSUE TITLE
sites are cached by the minter at container startup

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#317]
Sites are cached by the minter when the runtime container is started. When a new site is created and credentials are made and then a user tries to use the minter endpoint the code generates a 422 error with an error message of "Unknown requester $new_site" 

suggested resolution: the minter endpoint should refresh the list of sites at a regular interval

To reproduce:
Generate a new site with https://api.microbiomedata.org/docs#/sites/create_site_sites_post (ie minter_cache_test)
Generate credentials with https://api.microbiomedata.org/docs#/sites/generate_credentials_for_site_client_sites__site_id__generateCredentials_post
login w/client credentials 
use the minter endpoint to try to mint an id of any type w/o restarting rancher
https://api.microbiomedata.org/docs#/minter/mint_ids_pids_mint_post
Expected return error "Unknown requester minter_cache_test"

@eecavanna  did restart rancher yesterday and then I was able to mint an ID from the newly created site which is what @dwinston  had suggested to test the caching hypothesis. 

cc @brynnz22 @shreddd

**Comment by dwinston** [comment]
https://github.com/microbiomedata/nmdc-runtime/blob/a5338b176ca4c54f4d281a51fde51e7fb5b7ab5e/nmdc_runtime/minter/bootstrap.py#L19

the code in the bootstrap function from this line down needs to be re-run if the sites collection changes, so need to factor out this code into its own function and ensure it is called both on runtime bootstrap and on `POST /site`, the only other part of the codebase that dynamically (after boot) alters the sites collection.
