### ISSUE TITLE
Changesheet validator returns `HTTP 200` response even when reporting write errors

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#326]
API endpoint URL: https://api-dev.microbiomedata.org/metadata/changesheets:validate

Example problematic changesheet:

```tsv
id	action	attribute	value
nmdc:bsm-11-kyjye260	insert	gold_biosample_identifiers	gold:Gb0255534
```

Corresponding HTTP response body (excerpt):

```json
        "writeErrors": [
          {
            "index": 0,
            "code": 14,
            "errmsg": "The argument to $each in $addToSet must be an array but it was of type string"
          }
        ],
```

Screenshot:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/91926e5c-3e5e-468e-84a4-7fa904943741)

I expected the endpoint to return an HTTP 422 instead of an HTTP 200.

**Comment by aclum** [comment]
FYI @dwinston @eecavanna @shreddd  adding this to the sprint for next week as this is a high priority issue to get fixed. cc @sujaypatil96 @mbthornton-lbl

**Comment by dwinston** [comment]
returns 422 response with code fix. will link to PR.

```json
{
  "detail": {
    "update_cmd": {
      "nmdc:bsm-11-kyjye260": {
        "update": "biosample_set",
        "updates": [
          {
            "q": {
              "id": "nmdc:bsm-11-kyjye260"
            },
            "u": {
              "$addToSet": {
                "gold_biosample_identifiers": {
                  "$each": "gold:Gb0255534"
                }
              }
            }
          }
        ]
      }
    },
    "validation_errors": [
      [
        {
          "index": 0,
          "code": 14,
          "errmsg": "The argument to $each in $addToSet must be an array but it was of type string"
        }
      ]
    ]
  }
}
```

<img width="1255" alt="image" src="https://github.com/microbiomedata/nmdc-runtime/assets/1497854/e8b90dd0-d0e4-4401-9f56-9ae7b4f24dca">
