### ISSUE TITLE
Implement Python notebook for migration from `nmdc-schema` `8.0.0` to `8.1.2`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#335]
- [x] Implement the notebook to the extent possible (see next bullet point)
- [x] When a version of the `nmdc-schema` package that contains the necessary migration class has been released (ETA TBD), `import` that class and process its "agenda"

**Comment by eecavanna** [comment]
The transformation functions were introduced in `nmdc-schema` version `8.1.1`.

https://github.com/microbiomedata/nmdc-schema/compare/v8.1.0...v8.1.1#diff-e59e5c5787da889a611cbf193a0748d67682e0132b45966fbcb8559b3e058589R271

**Comment by ssarrafan** [comment]
Appears to be active. Will move to next sprint. @eecavanna let me know if this should go in the backlog instead.  Thanks!

**Comment by eecavanna** [comment]
It is active. Next sprint works for me. Thanks!
