### ISSUE TITLE
Implement Python notebook for migration from `nmdc-schema` `8.1.2` to `9.0.4`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#336]
- [ ] Implement the notebook to the extent possible (see next bullet point)
- [ ] When a version of the `nmdc-schema` package that contains the necessary migration class has been released (ETA TBD), `import` that class and process its "agenda"

**Comment by eecavanna** [comment]
Based on the line of code in a PR below...

https://github.com/microbiomedata/nmdc-schema/pull/1208/files#diff-e59e5c5787da889a611cbf193a0748d67682e0132b45966fbcb8559b3e058589R301

...I think the `NEXT` version will be `9.0.0`.

**Comment by turbomam** [comment]
I was going to make the next nmdc-schema v8.2.0. Is there a reason you think we should do a major jump? We ahven't been consistent, so your input is welcome. I just fear that incrementing the major version on every breaking change will mean very fast growth in that position.

**Comment by eecavanna** [comment]
>Is there a reason you think we should do a major jump?

The reason I updated the name of this Issue from `NEXT` to `9.0.0` was to match [the PR](https://github.com/microbiomedata/nmdc-schema/pull/1208/files#diff-e59e5c5787da889a611cbf193a0748d67682e0132b45966fbcb8559b3e058589R301).

I don't think the `nmdc-schema` documentation advertises that the version identifier is anything other than an arbitrary number that increases over time (as opposed to, for example, a [semantic versioning](https://semver.org/) identifier—where the major, minor, and patch segments have some standard meanings tied to them). Based on that, I'm OK with both `9.0.0` and `8.2.0`.

> I just fear that incrementing the major version on every breaking change will mean very fast growth in that position.

For future reference, I'm OK with fast growth / large numbers in the major position (e.g. I'm OK getting to `1234.0.0` and beyond).

**Comment by eecavanna** [comment]
Note: The transformation functions were introduced in `nmdc-schema` release `9.0.0`.

https://github.com/microbiomedata/nmdc-schema/compare/v8.1.2...v9.0.0#diff-e59e5c5787da889a611cbf193a0748d67682e0132b45966fbcb8559b3e058589R301

**Comment by ssarrafan** [comment]
Appears to be active. Will move to next sprint. @eecavanna let me know if this should go in the backlog instead.  Thanks!

**Comment by eecavanna** [comment]
It is active. Next sprint works for me. Thanks!
