### ISSUE TITLE
Checksum Matches Existing Object - Json submit endpoint

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-runtime#340]
When trying to re-submit a JSON that was previously deleted from production, I encounter the error:

`detail": "provided checksum matches existing object: {'checksums.type': 'sha256', 'checksums.checksum': '9eaece59f58b4d58008f2efcf556736c0f5a0cbe16311206d7f6b127e9cfc580'}`

**Comment by dwinston** [comment]
There is a workaround — I can locate the past dagster job that sourced your submitted json and then re-run it (e.g. via the dagster dagit UI). However, I recognize that re-submitting is a legitimate use case, so I’d rather change the code to e.g. include a timestamp in the submission so that the resulting payload has a unique checksum.

**Comment by brynnz22** [comment]
Thank you @dwinston apologies for not reviewing this sooner. I attempted to resubmit a json just now that I had previously submitted and then deleted from MongoDb weeks ago and I get the same error: 

`{
  "detail": "provided checksum matches existing object: {'checksums.type': 'sha256', 'checksums.checksum': '9eaece59f58b4d58008f2efcf556736c0f5a0cbe16311206d7f6b127e9cfc580'}"
}`

**Comment by eecavanna** [comment]
I'm posting this comment to confirm that the production Runtime API is currently at commit: 0c69b60a6bb6cae46ea976f2d74a64893117273d

<img width="607" alt="image" src="https://github.com/microbiomedata/nmdc-runtime/assets/134325062/45c8216a-9a16-4682-bbdf-4f03fb2f8377">

**Comment by dwinston** [comment]
plan: add an optional timestamp kwarg to https://github.com/microbiomedata/nmdc-runtime/blob/21393c5815fd29abfcefd8eb99d174e6317ad0e0/nmdc_runtime/api/core/util.py#L31 so that the same content submitted at a different time generates a different checksum.

**Comment by dwinston** [comment]
then, add a `str` of the current time to this invocation:

https://github.com/microbiomedata/nmdc-runtime/blob/21393c5815fd29abfcefd8eb99d174e6317ad0e0/nmdc_runtime/api/endpoints/util.py#L435C21-L435C21
