### ISSUE TITLE
Update `@root_validator` to `@model_validator` in API Models

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#341]
From: https://github.com/microbiomedata/nmdc-runtime/issues/337

`@root_validator` is deprecated and should be replaced with `@model_validator`.

Refactoring required in 
- nmdc_runtime/api/models/id.py 
- nmdc_runtime/api/models/object.py
- nmdc_runtime/api/models/query.py

**Comment by dwinston** [comment]
should be “covered” by #339.
