### ISSUE TITLE
Swagger UI does not submit HTTP request to API server

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#343]
At least for some endpoints (all that I've tried so far), Swagger UI is not submitting the HTTP request to the API server. Instead, an error about data validation is appearing in the JS console. Here's a screenshot showing the error.

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/ebc9c82f-7ae6-4c3c-bb7c-7fa01ef9d9a5)

Background:
- `nmdc-runtime` was updated earlier today to use a version of FastAPI that works around yesterday's Swagger UI issue. As a result, that Swagger UI problem stopped affecting us and we were able to access previously-inaccessible sections of the Swagger UI. The web page isn't hanging anymore.
- That `nmdc-runtime` update seems to have introduced this new issue (see introductory paragraph above) affecting Swagger UI usage.

More details are on Slack, at: https://nmdc-group.slack.com/archives/C05EFGHCYRH/p1698791445508619

**Comment by eecavanna** [comment]
While creating this Issue, I wanted to cite a version number of `nmdc-runtime`. Since it currently doesn't have version numbers (see related [ticket](https://github.com/microbiomedata/nmdc-runtime/issues/302)), I will cite the commit hash instead.

Here's the commit hash where this issue is present: f097bdd48304b30d2d287dbf89a9ddadb75a74e4

**Comment by dwinston** [comment]
I suspect this is an outcome of point 9 from https://github.com/microbiomedata/nmdc-runtime/issues/337#issuecomment-1787375719. That is, a pydantic field specification like `filter: Optional[str]` [no longer means a field is optional](https://docs.pydantic.dev/2.4/migration/#required-optional-and-nullable-fields). For pydantic V2, one needs to specify e.g. `filter: Optional[str] = None`. The first form now (in pydantic V2) seems to mean "this field is required, and its value may be a `str` or the value `None`".
