### ISSUE TITLE
API endpoint `/queries:run` returns HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#350]
Swagger UI link:
https://api.microbiomedata.org/docs#/queries/run_query_queries_run_post

The request payload is:

```json
{
"find": "biosample_set",
"filter": {"gold_biosample_identifiers": {"$elemMatch":{"$eq": "gold:Gb0356184"}}}
}
```

Here's a screenshot of the error response on Swagger UI:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/d93b9185-5bc3-4db0-8ca8-382051c0d27f)

The final few lines of the stack trace on the server are:

```py
  File "/code/nmdc_runtime/api/endpoints/queries.py", line 79, in run_query
    cmd_response = _run_query(query, mdb)
  File "/code/nmdc_runtime/api/endpoints/queries.py", line 141, in _run_query
    mdb.query_runs.insert_one(query_run.model_dump(mode="json", exclude_unset=True))
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'bson.objectid.ObjectId'>
```

Full stack trace is on Slack, here: 
https://nmdc-group.slack.com/archives/C05966WE4G6/p1698979668327079?thread_ts=1698960484.010949&cid=C05966WE4G6

Originally reported by @mbthornton-lbl on Slack, here:
https://nmdc-group.slack.com/archives/C05966WE4G6/p1698960484010949

CC: @PeopleMakeCulture

**Comment by dwinston** [comment]
fixed by #363
