### ISSUE TITLE
revisit endpoints used to update mongo data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#356]
I'd like to revisit alternatives to changesheets, for example, perhaps an endpoint which would take pymongo find and update commands directly.
To be discussed an an upcoming infrastructure sync

cc @shreddd @eecavanna @dwinston @mbthornton-lbl @brynnz22 @mslarae13 @ssarrafan

**Comment by ssarrafan** [comment]
Adding to next sprint to discuss at infra sync mtg.

**Comment by ssarrafan** [comment]
Adding to sprint 25 due to holiday and other priorities.

**Comment by ssarrafan** [comment]
> Did this discussion happen? I think I missed it.. but I'm interested in the point made

@mslarae13 No it didn't happen. I've added it to the infra sync meeting agenda for next week.

**Comment by dwinston** [comment]
Could potentially accept update requests using format of https://www.mongodb.com/docs/v6.0/reference/command/update/#mongodb-dbcommand-dbcmd.update and allow a subset of what's possible.

**Comment by eecavanna** [comment]
Some notes from the infrastructure sync:
- https://github.com/INCATools/kgcl (mentioned by @turbomam)
- https://incatools.github.io/kgcl/examples/
- https://dictdiffer.readthedocs.io/en/latest/ (mentioned by @eecavanna)

@dwinston also mentioned there is an endpoint that people can use to replace entire documents; so, if they first fetch the original document, they could make the changes they want, then submit that via that endpoint.
