### ISSUE TITLE
Reconfigure GitHub Actions to have separate dev and production deployments

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-runtime#357]
Currently we have:

* A `build-and-push-docker-images` [workflow](https://github.com/microbiomedata/nmdc-runtime/blob/dc668eaa9efb210336947673a9df379ccaf2b9f1/.github/workflows/build-and-push-docker-images.yml) which runs either manually or automatically on pushes to `main`. As the name suggests, it builds Docker images and pushes them to Docker Hub.
* A `release-to-spin` [workflow](https://github.com/microbiomedata/nmdc-runtime/blob/dc668eaa9efb210336947673a9df379ccaf2b9f1/.github/workflows/release-to-spin.yml) which is triggered by the successful completion of the `build-and-push-docker-images` workflow. This workflow issues Rancher CLI commands (via [this action](https://github.com/colbyhill21/Rancher-Action)) to restart the `runtime-api`, `dagster-dagit`, and `dagster-daemon` deployments on dev and production. These deployments all pull the `main`-tagged images.

The effect of this is that PR merges (or direct pushes to `main`) are immediately deployed to both dev and production. This is a double-edged sword. We can quickly get backwards-compatible fixes out quickly, but there's also no guard against backwards-incompatible changes going out before downstream clients are ready.

The proposal here is to move to a model where:

* Deployments to dev happen immediately on pushes to `main`, as happens today
* Deployments to production are pinned to tagged release versions

In a perfect world the only manual action needed to do a production deployment would be creating a GitHub release and everything else would happen automatically. That might not be possible at the moment because of manual operations needed for data migration when the `nndc-schema` dependency changes. We should automate as much as possible and [clearly document](https://github.com/microbiomedata/infra-admin/issues/19) the rest.

This task is to do any updates to workflows in this repo and configuration in Racher to support deploying tagged versions to production.

**Comment by pkalita-lbl** [comment]
The actions should also produce informatively tagged Docker images. See: https://github.com/microbiomedata/nmdc-runtime/issues/359

**Comment by shreddd** [comment]
I think this is more or less what I had in mind. Thanks for doing this.
