### ISSUE TITLE
Tag container images with `x.y.z` version identifier (so DockerHub matches GitHub and PyPI)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#359]
Currently, the "version identifiers" that appear on DockerHub are commit hashes (see screenshot). Meanwhile, the "version identifiers" that appear on PyPI and GitHub are `x.y.z`-style identifiers.

DockerHub vs. PyPI:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/65b23aae-04fd-44bc-a5f9-5ff0c8b28cef)

GitHub:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/4f3c63be-5681-40c9-b25b-90f48eaead9e)

I propose we tag container images with the same `x.y.z` version identifier as is used on GitHub and PyPI.

### Links

- DockerHub page: https://hub.docker.com/r/microbiomedata/nmdc-runtime-fastapi/tags
- PyPI page:  https://pypi.org/project/nmdc-runtime/

**Comment by pkalita-lbl** [comment]
I think this can be taken care of in #357 but we can keep both issues open just to make sure it gets done

**Comment by eecavanna** [comment]
Related: https://github.com/microbiomedata/nmdc-runtime/issues/372

**Comment by dwinston** [comment]
done via #357 et al.
