### ISSUE TITLE
API endpoint `/version` does not return same version identifier as Swagger UI heading or GitHub or PyPI

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#372]
Here's a screenshot showing all of them as of now:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/7b3e5db0-3ec5-4489-a595-71000b50ce12)

**Comment by dwinston** [comment]
right. for some reason, unstashed and unstaged changes are present in the deployed-container git repo directory, making introspection not return e.g. `v1.0.9`. I suspect that the right mods to https://github.com/microbiomedata/nmdc-runtime/blob/4561d854e31291fab40cd7377c52eb62986e0683/docker-build.sh will fix this and #359

**Comment by dwinston** [comment]
it seems that something "extra" is being done to the git working directory on deploy. See below screenshots re: this curious discrepancy.

/cc @pkalita-lbl 

<img width="1069" alt="image" src="https://github.com/microbiomedata/nmdc-runtime/assets/1497854/13f4c100-c30a-4d8f-8917-90fc644ff4f1">

<img width="714" alt="image" src="https://github.com/microbiomedata/nmdc-runtime/assets/1497854/53c30677-d3a9-43dc-be97-5e6335351e03">

**Comment by dwinston** [comment]
FYI I now have the prod workloads using the `microbiomedata/nmdc-runtime-fastapi:prod` image\.

**Comment by dwinston** [comment]
a couple options:

1. execute `git reset --hard` in the container
2. include the `deleted` files in the container (i.e. ensure they pass the rejections of `.dockerignore`)

**Comment by pkalita-lbl** [comment]
With this change in main I can see the correct `.dev` version number on the docs page here: https://api-dev.microbiomedata.org/docs and from the endpoint here: https://api-dev.microbiomedata.org/version

I'm pretty confident we'll see the right version numbers on prod once the next release happens.
