### ISSUE TITLE
use NMDC_CLIENT_ID env var in prod

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-runtime#415]
Enable NMDC_CLIENT_ID variable in production to read ORCID client ID information. 

This is already enabled in Rancher so the code just needs to read this from the environment.

**Comment by dwinston** [comment]
this repo uses `ORCID_CLIENT_ID` for that. And that has now been done. If uniformity of env var names across services is desired, please open as separate issue. Also noting here that client ids are okay to be public, so I put the runtime's env var for this in a ConfigMap, not in a Secret.
