### ISSUE TITLE
runtime issues when running changesheets:validate when record has legacy ID

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#416]
I'm not sure we want to fix this given re-iding should be happening shortly but just wanted to note this. I get a validation error about the has_input and part_of because of the prefixes when I try to update a legacy records has_output value to a napa complaint ID. The previous behavior was that you could not submit new records with legacy IDs but you could update those records with changesheets. I believe this is caused by some of the work @turbomam I asked for for the napa compliance squad  to make sure not just IDs but also ID mentions in other slots conform to napa style identifiers.

Test changesheet

id | action | attribute | value
-- | -- | -- | --
emsl:500163 | update | has_output | nmdc:dobj-11-4kwfhk83

validation error against changesheet:validate runtime API prod endpoint
{
  "detail": {
    "update_cmd": {
      "emsl:500163": {
        "update": "omics_processing_set",
        "updates": [
          {
            "q": {
              "id": "emsl:500163"
            },
            "u": {
              "$set": {
                "has_output": [
                  "nmdc:dobj-11-4kwfhk83"
                ]
              }
            }
          }
        ]
      }
    },
    "validation_errors": [
      [
        "'gold:Gb0126444' does not match '^nmdc:(bsm|procsm)-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\\\.-]+)?$'",
        "'gold:Gs0114663' does not match '^nmdc:sty-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\\\.-]+)?$'"
      ]
    ]
  }
}

@turbomam  let me know if this should be moved from a nmdc-runtime issue to a nmdc-schema issue.

---

_Edit: @eecavanna added this "[Formatted](https://jsonformatter.org/)" version of the above JSON snippet:_

```json
{
  "detail": {
    "update_cmd": {
      "emsl:500163": {
        "update": "omics_processing_set",
        "updates": [
          {
            "q": {
              "id": "emsl:500163"
            },
            "u": {
              "$set": {
                "has_output": [
                  "nmdc:dobj-11-4kwfhk83"
                ]
              }
            }
          }
        ]
      }
    },
    "validation_errors": [
      [
        "'gold:Gb0126444' does not match '^nmdc:(bsm|procsm)-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})([A-Za-z0-9\\.-]+)?$'",
        "'gold:Gs0114663' does not match '^nmdc:sty-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})([A-Za-z0-9\\.-]+)?$'"
      ]
    ]
  }
}
```

**Comment by dwinston** [comment]
It seems reasonable to exclude the `id` field from validation for changesheets, as each change is keyed on a de-facto-valid `id` (i.e. found in the database), and no change can alter that `id`.

What do you think? /cc @turbomam @eecavanna @PeopleMakeCulture

**Comment by eecavanna** [comment]
The only corner case I have come up with for when "excluding the `id` field from validation for changesheets" might come back to bite us is: a changesheet making a change to some _other_ field that would cause a previously-valid `id` to become invalid, due to some (hypothetical) "cross-field" dependency (e.g. `id` value must start with the value of the `prefix` field). I don't know whether such "cross-field" dependency is even a thing when it comes to the schema/schema-based validation.

Other than that, I don't have any concerns with it, as along as changesheets can't alter `id` values.

**Comment by aclum** [comment]
The changes made to the API queries: run last month  to provide update statements provide a workaround for this issue w/o any changes needed. I propose closing this as won't fix since we can use queries: run until the re-iding is complete.

**Comment by eecavanna** [comment]
Closing this as "won't fix" works for me. I remember (after reading the original issue description this morning) that you had initially posted it more as a note than a request that it be fixed.

**Comment by eecavanna** [comment]
Closing as "won't fix." We may reopen this if it begins impacting people's work.

**Comment by aclum** [comment]
Just a note that Brynn said this was working over chat so maybe Donny changed something on the backend already? In any case we can leave this closed.
