### ISSUE TITLE
Update mdb backup permissions on CFS

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#422]
See: https://nmdc-group.slack.com/archives/C05EFGHCYRH/p1702960113384549

The directory containing the MongoDB backups on CFS has these permissions:
```
[cavannae@dtn01 m3408]$ ls -al /global/cfs/cdirs/m3408/ | grep mongo
drwxrwsrwx   160 dwinston m3408      16384 Dec 18 12:12 nmdc-mongodumps
```
I interpret the rightmost `w` to mean that "other" users (i.e. anyone with a NERSC account) can delete the contents of that directory.

**Comment by dwinston** [comment]
no longer "world"-readable (or writeable). thanks.
```
[dwinston@dtn01 m3408]$ ls -dl nmdc-mongodumps
drwxrws--- 163 dwinston m3408 16384 Dec 19 18:01 nmdc-mongodumps
```
