### ISSUE TITLE
Add API documentation to help users with current auth flow(s)

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#428]
### Short-term:
Add documentation to Swagger UI to help users select the proper way to authenticate 

From @turbomam:

> As part of this refactoring, can the user help in the Swagger Authorize button be updated? For example, could it say which authorization method supports the use of an ORICID, and what the flow is in terms of entering the ORCID (and whetehr it should be a bare ID or should include the prefix), being redirected to another page, copying a token, and then pasting that back into the Swagger Authorize dialog?
> 
> I know we have been given walk-throughs on this, but I'm just wondering if there is some documentation or videos I can refer back to. If not, it would be nice to have some hints in the Swagger Authorize dialog.

**Comment by dwinston** [comment]
@PeopleMakeCulture can you re-title this issue to be more narrowly about adding documentation to help users with the current auth flow(s), and move the "mid-term" content (I like the clear mock-up) to  #423 ?

**Comment by PeopleMakeCulture** [comment]
@turbomam I'm deprecating this issue as the new API release will include a single-click sign on. Video documentation here: https://files.polyneme.xyz/runtime-swagger-orcid-auth-cookie-based-1705958479.mp4

For the current production API (in use until Jan 29), please use the previous username/password or client_id/client_secret flows.
