### ISSUE TITLE
Migrations: Implement bookkeeping so database tells us which schema it conforms to

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#432]
In other words, the database would "know" (tell us) what migrations have been applied to it; or at least which one was applied to it most recently.

**Comment by eecavanna** [comment]
I plan to implement this as part of the standard code run by the Python notebooks used for migration. The notebooks could create a document at the beginning of the migration process; something like: `{ "from": __, "to": __, "start_time": "...", "end_time": null }`. Then, at the end of the migration process, the notebook could update the document to have an `end_time`. To determine the current schema version, a user could sort the documents by their `end_time`. Alternatively (or in addition), the notebook could also update some singleton `to` field to indicate the schema version to which the database was updated most recently. Then, a user could check that single `to` field as a quick way of checking (effectively) what schema version the database is "at".

**Comment by eecavanna** [comment]
Sprint planning note: There's a chance that this will be done on Friday afternoon, but I think it's more likely that it will spill over into next sprint.

**Comment by ssarrafan** [comment]
Moving to next sprint @eecavanna
