### ISSUE TITLE
co-locate as much API usage documentation with OpenAPI spec and thus on Swagger display

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#437]

**Comment by dwinston** [comment]
e.g. migrate content from https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md to this repo

**Comment by PeopleMakeCulture** [comment]
PR: https://github.com/microbiomedata/nmdc-runtime/pull/455

**Comment by PeopleMakeCulture** [comment]
TODO: @PeopleMakeCulture to make PR to https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md 

- [ ] add API version 
- [ ] remove documentation for old endpoints
- [ ] invite/request documentation on new endpoints (eg find/data_objects/study/study_id)

**Comment by dwinston** [comment]
@PeopleMakeCulture #455 was merged. Can this issue be closed?

**Comment by PeopleMakeCulture** [comment]
I'd like to keep it open as a reminder to monitor a couple loose ends (in checklist above)
