### ISSUE TITLE
use `ORCID_NMDC_CLIENT_{ID,SECRET}` for ORCiD credentials

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#445]
Slack conversation: https://nmdc-group.slack.com/archives/C05EFGHCYRH/p1705957725732599

![Image](https://github.com/microbiomedata/nmdc-runtime/assets/26777878/4a118a6b-8c08-4dc5-bfea-2c60b51324ff)

i.e. use the `orcid-member-auth` k8s secret with prefix `ORCID_` in the workload env vars config. Migrate from `ORCID_CLIENT_{ID,SECRET}`.

Related to: #415 use NMDC_CLIENT_ID env var in prod 

@PeopleMakeCulture seems like a quick PR. Could you take this?

**Comment by PeopleMakeCulture** [comment]
PR: https://github.com/microbiomedata/nmdc-runtime/pull/446

@dwinston I still don't have SPIN access so I wasn't able to verify a match to the env vars on Spin. Could you confirm?

**Comment by dwinston** [comment]
waiting on upstream update of ORCiD account redirect URIs to include api-dev.microbiomedata.org
