### ISSUE TITLE
CI/CD should include tests for endpoints used in example notebooks

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-runtime#456]
We want to make sure the example notebooks in this repo: https://github.com/microbiomedata/notebook_hackathons do not break with any changes or pushes to the NMDC-runtime API. 

The following endpoints are used (with example tests).

- [ ] *find studies endpoint* https://api.microbiomedata.org/studies?filter=name.search:DP1.10107.001
- [ ] *find biosamples endpoint* https://api.microbiomedata.org/biosamples?filter=part_of:nmdc:sty-11-34xj1150&per_page=10&cursor=*&fields=ph,collection_date.has_raw_value,env_medium,geo_loc_name,lat_lon,water_content,soil_horizon,elev
- [ ] *metadata collection_name endpoint* https://api.microbiomedata.org/nmdcschema/biosample_set?&max_page_size=100&projection=id,soil_horizon,geo_loc_name

**Comment by kheal** [comment]
@brynnz22 - can you also add an example of the endpoint you used to download the tsvs of the taxonomic information?  I couldn't figure out an easy way to access the url for this step.  The url I'm talking about is in code chunk 30 in [this notebook](https://nbviewer.org/github/microbiomedata/notebook_hackathons/blob/main/taxonomic_dist_by_soil_layer/python/taxonomic_dist_soil_layer.ipynb).

**Comment by brynnz22** [comment]
@kheal that url was just taken from the metadata retrieved using the _metadata collection _endpoint__ that you already mentioned.

**Comment by kheal** [comment]
Great - so the three endpoints I point to above will cover the API calls we've used in the notebook, correct?  @brynnz22

**Comment by brynnz22** [comment]
Yep! That should be right.

**Comment by PeopleMakeCulture** [comment]
Related to #301

**Comment by PeopleMakeCulture** [comment]
@kheal Is this the example notebook you're referring to in your first comment? https://github.com/microbiomedata/notebook_hackathons/tree/main/taxonomic_dist_by_soil_layer

**Comment by kheal** [comment]
@PeopleMakeCulture  - that is one of the notebooks.  

These two also use the runtime API: https://github.com/microbiomedata/notebook_hackathons/tree/main/NEON_soil_metadata and https://github.com/microbiomedata/notebook_hackathons/tree/main/bioscales_biogeochemical_metadata (in both the R and python versions, for a total of 5 notebooks).  

Do you want/need me to point to each chunk in each notebook (5 notebooks total) that pings the API?

**Comment by PeopleMakeCulture** [comment]
@kheal Gotcha. The notebook links should be enough. Thanks!

**Comment by kheal** [comment]
@dwinston No, [this notebook ](https://github.com/microbiomedata/notebook_hackathons/tree/main/taxonomic_dist_by_soil_layer) takes several hours (in part bc there is not an easy API route to go from biosample ids to data objects, see #355.  That notebook takes a couple hours to run, so I don't think you want to include the whole thing.

The get requests I have at the top of this thread are type examples and should be sufficient as tests to make sure the endpoints are still good.

**Comment by shreddd** [comment]
We should discuss potential notebook testing options as well, and what makes the most sense. I have some folks in my group who have experience with other Jupyter testing tools like nbmake (https://github.com/treebeardtech/nbmake) 

Also fine with papermill but the typical papermill use case I've seen is centered around running a notebook job in parallel where it gets parameterized different inputs. Just want to confirm we are using the right tool for the job.

I've also seen this (from the same people at Netflix that made papermill) - https://github.com/nteract/testbook

**Comment by kheal** [comment]
I should have noted that the other four notebooks in these locations
https://github.com/microbiomedata/notebook_hackathons/tree/main/NEON_soil_metadata and https://github.com/microbiomedata/notebook_hackathons/tree/main/bioscales_biogeochemical_metadata are pretty quick and it'd be great to have those tested in the CI/CD.

**Comment by kheal** [comment]
FYI @dwinston @shreddd @PeopleMakeCulture - I've added some CI/CD to check the notebooks' stability via gh actions to the notebook repo (https://github.com/microbiomedata/nmdc_notebooks/pull/61).  I'm not sure exactly how to add these checks (or something) similar to test to changes to the runtime during dev, but I wanted to let you all know. I've scheduled the test for 1/week (as well as for PRs within the https://github.com/microbiomedata/nmdc_notebooks repo).

**Comment by PeopleMakeCulture** [comment]
@kheal IIRC all runtime API endpoints in the notebooks are currently covered by existing API endpoint tests, but we do not perform an end-to-end run of the notebooks as part of the runtime's CI pipeline (what you have in https://github.com/microbiomedata/nmdc_notebooks/pull/63 in the notebooks repo. 

It is possible for a trigger in one repo (eg a pull request) to trigger a gh action in another. Here is a [discussion](https://github.com/orgs/community/discussions/26323#discussioncomment-3251448) on how to implement, with examples.

I'm pulling this ticket off the bench for now
