### ISSUE TITLE
coordinate range-attribute schema changes with Kitware prior to ETL

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#46]
For attributes that hold ranges (e.g., `depth`, `depth2`), the schema has been changed (see #44) so that min/max of the range is represented like so:
```
     depth: 5.0-10.0
      has_unit: meter
      has_minimum_numeric_value: 5.0
      has_maximum_numeric_value: 10.0
```
Before pushing the changed docs to production we need to make sure Kitware can ingest the new docs.

Steps:
- [ ] Ingest new ETL into Mongo (i.e., run the the dagster operations)
- [ ] Add post-ETL modifications (e.g., change sheets, or notebooks)
- [ ] Coordinate with Kitware to download the changed docs (in the biosample collection)
- [ ] Verify that new data is ingested into portal
- [ ] Remove old `depth2` and `subsurface_depth2` attributes (see https://github.com/microbiomedata/nmdc-schema/issues/193)

cc @dwinston @jeffbaumes @subdavis

**Comment by ssarrafan** [comment]
@wdduncan I will move this to November since we haven't been able to work with Kitware for a couple of weeks.  

If this should be moved to the backlog instead let me know.

**Comment by ssarrafan** [comment]
Moving this to the December sprint since Kitware isn't currently available and @wdduncan said he is blocked waiting to be able to work with them.

**Comment by ssarrafan** [comment]
@wdduncan would you like to discuss this at this Thursday's infrastructure sync with the Kitware team?  I'm going to remove Donny from this issue since he's out.

**Comment by ssarrafan** [comment]
Re-assigning this to @sujaypatil96 but please let me know if this is not a priority for March and we can move it the backlog. 

FYI: @cmungall @turbomam 

Note from Bill:
HI Set. Here is an update:
https://github.com/microbiomedata/nmdc-schema/issues/134
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-runtime/issues/89
I updated the comment on this. I should be able to get the change sheet edit done before I leave.
https://github.com/microbiomedata/nmdc-schema/issues/195
I am working with Sujay on this. I should be able to close before the week’s end.
https://github.com/microbiomedata/nmdc-runtime/issues/46
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-server/issues/555
This is a lot of conversation in this thread. But, it looks like Mark has taken this one over.

**Comment by ssarrafan** [comment]
Moving out of the sprint, adding backlog label per @sujaypatil96
