### ISSUE TITLE
add github users to architecture working group team

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#47]
1. invite @kfox1111 and @elais to to the <https://github.com/microbiomedata> github org
2. add them to the @microbiomedata/architecture-wg team.

@ssarrafan can you please do (1)? I can do (2).

**Comment by ssarrafan** [comment]
<img width="1031" alt="Screen Shot 2021-10-29 at 11 09 39 AM" src="https://user-images.githubusercontent.com/79225425/139482414-9417d501-4971-49dc-860a-cc4e33aea551.png">
They've been added to the org @dwinston

**Comment by ssarrafan** [comment]
<img width="482" alt="Screen Shot 2021-10-29 at 11 11 38 AM" src="https://user-images.githubusercontent.com/79225425/139482606-0f621834-0139-49e9-89e5-a864efcf1036.png">

Also added them to the architecture-wg team.  Will close this issue.
