### ISSUE TITLE
GitHub Action workflow ran for 6 hours (before being terminated)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#489]
Log: 

https://github.com/microbiomedata/nmdc-runtime/actions/runs/8148876894/job/22272559292

Screenshot:

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/742cf328-09a6-49fb-8c22-009714bb82bd)

Last few lines of output (I don't mean to imply that this is the stage of the workflow that consumed all those hours):

```sh
tests/e2e/test_minter_api.py xxxx                                        [  4%]
tests/integration/test_minter_repository.py ....X...                     [ 13%]
tests/test_api/test_db_mongo.py .....                                    [ 19%]
Error: The operation was canceled.
```

**Comment by PeopleMakeCulture** [comment]
The `test_create_user()` has been disabled. We believe that this test was causing the test suite to hang. Specifically, this test contains a [retry strategy](https://github.com/microbiomedata/nmdc-runtime/blob/469e37d3f0bdaafa6dfa67a37fad00ccc82714a5/tests/test_api/test_endpoints.py#L96) to fetch a user token that may have led to the tests timing out
