### ISSUE TITLE
changesheet validator throws error when using `remove item` for a single-value field

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#498]
@brynnz22 submitted a bug with the `changesheet:validates` endpoint, where the validator throws an error when using `remove item` with a single-value field

**Comment by dwinston** [comment]
The correct action to specify for this intent is `remove` (or `delete`), as per this code block:

https://github.com/microbiomedata/nmdc-runtime/blob/v1.4.1/nmdc_runtime/api/core/metadata.py#L505-L530

However, this action is missing from the how-to guide:

https://github.com/microbiomedata/nmdc-runtime/blob/v1.4.1/docs/howto-guides/author-changesheets.md
