### ISSUE TITLE
Add banner to swagger ui

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#506]
Swagger UI banners may be useful to let users know of planned outages.   

See convo in Slack: https://nmdc-group.slack.com/archives/C01034ES34G/p1713385971393999

**Comment by PeopleMakeCulture** [comment]
Related to this branch in `nmdc-server`: https://github.com/microbiomedata/nmdc-server/tree/app-banner

NOTE: The proposed method for updating banner text is to update an env variable in Rancher. However currently the banner text is hard-coded

**Comment by eecavanna** [comment]
I think this is done as of commit https://github.com/microbiomedata/nmdc-runtime/issues/506

**Comment by dwinston** [comment]
done via #507
