### ISSUE TITLE
Loosen CORS restrictions to allow access from browser-based clients

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#508]
I built a web-based dashboard team members can use to see the version numbers of NMDC services, all in one place. The dashboard fetches the version numbers via each service's `/version` (or similar) endpoint. For example, to fetch the version number of the production Runtime API, it sends a request to: https://api.microbiomedata.org/version

When I serve the dashboard from `https://localhost:*` (e.g. during development), those fetches work. In contrast, when I serve the dashboard from `https://*.github.io` (i.e. when it is hosted on GitHub Pages and visited via the GitHub-provided URL), those fetches do not work. In the latter case, the web browser reports CORS errors.

I see the Runtime API has the following hostnames on its "allow list" (which explains the above behavior to me):

https://github.com/microbiomedata/nmdc-runtime/blob/6936534cbc66463df68d781ab6a69fb2a207bd30/nmdc_runtime/api/main.py#L444

I am creating this ticket to represent the task of loosening the CORS restrictions of the Runtime API so that an application running in a web browser (accessed via something other than `http://localhost:*` or `https://*.microbiomedata.org`) can fetch its version information.

Here are some ways that could be accomplished:

1. Add `https://*.github.io` to the "allow list"
2. Add `https://{username}.github.io` to the "allow list"
   - I don't want to do this because I don't want the Runtime API to give my GitHub username special treatment
3. Add `https://*.github.io` to the "allow list" **only for the version check endpoint**
   - I don't know whether FastAPI allows for endpoint-specific middleware settings
5. Add `https://{username}.github.io` to the "allow list" **only for the version check endpoint**
   - I don't want to do this because I don't want the Runtime API to give my GitHub username special treatment
   - I don't know whether FastAPI allows for endpoint-specific middleware settings

Here's another option, which doesn't involve modifying the Runtime API:

1. Host the dashboard at a `https://*.microbiomedata.org` URL
   - I don't want to do this yet because the dashboard also depends upon an individual's Rancher API key, and I don't want to host something under `https://*.microbiomedata.org` that is dependent upon an individual's secret

**Comment by eecavanna** [comment]
For reference, the `nmdc-server` project uses an environment variable (i.e. `NMDC_CORS_ALLOW_ORIGINS`) to control what origins it accepts requests from. Here's an example definition/value: https://github.com/microbiomedata/nmdc-server/blob/862e157e379e0406623577faea24007ce35d3491/.env.example#L19

**Comment by dwinston** [comment]
@eecavanna go ahead and fold `microbiomedata.github.io` into `allow_origin_regex` as a PR, as you suggested in Slack.
