### ISSUE TITLE
Delete `read_based_analysis_activity_set` collection from production Mongo server

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#539]
`read_based_analysis_activity_set` is an old collection, there 912 records which are duplicated in the more complete collection, `read_based_taxonomy_analysis_activity_set`.

`read_based_taxonomy_analysis_activity_set` is what is currently specified as the range for Database slot [`ReadBasedTaxonomyAnalysisActivity`](https://microbiomedata.github.io/nmdc-schema/ReadBasedTaxonomyAnalysisActivity/). 

`read_based_analysis_activity_set` contains legacy identifiers and causes confusion so I'd like it removed.

remove: `read_based_analysis_activity_set` (912 documents)
keep: `read_based_taxonomy_analysis_activity_set` (2234 documents as of 5/28/24)

**Comment by eecavanna** [comment]
I'll do this today and report back when done.

**Comment by eecavanna** [comment]
Done.

### Before

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/f1004422-50d8-4bb6-b666-050f0ade9800)

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/2eac74e5-2829-4e61-b310-9d4f81fa9a0c)

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/a74bbba6-46a3-45ad-9f7d-85f71d5870b5)

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/48e0e6a0-276e-4cf9-acb5-98245eb285b8)

### After

![image](https://github.com/microbiomedata/nmdc-runtime/assets/134325062/ff2b5427-77fc-48e5-8878-32aa4cd9d3d7)
