### ISSUE TITLE
Run Ref Integrity Notebook on post-re-iding Mongo

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#555]

**Comment by PeopleMakeCulture** [comment]
Deprecate `nmdc_schema_accepting_legacy_ids` to  in: 

- [ ] bulk referential integrity check notebook  
- [ ] [`validate_json` util](https://github.com/microbiomedata/nmdc-runtime/blob/89a580244989f3138f3e3797c619fd55e42b244c/nmdc_runtime/util.py#L578)
- [ ] Test `validate_json`

```python
# from nmdc_schema.nmdc_schema_accepting_legacy_ids import Database as NMDCDatabase
from nmdc_schema.nmdc import Database as NMDCDatabase
```

**Comment by aclum** [comment]
Make sure nmdc-schema v10.5.5 is used, that will resolve some of the type errors for DataObject was_generated_by values that were being discussed at the infrastructure meeting on Thursday.

**Comment by PeopleMakeCulture** [comment]
> Make sure nmdc-schema v10.5.5 is used, that will resolve some of the type errors for DataObject was_generated_by values that were being discussed at the infrastructure meeting on Thursday.

What's the best way to introspect about the schema version I'm importing?

**Comment by PeopleMakeCulture** [comment]
I re-ran the Bulk Validation and Ref Integrity notebook after updating `nmdc-schema==10.5.5` in `nmdc-runtime/requirements/main.in`. Here are the new results:

```python
len(errors["not_found"]), len(errors["invalid_type"])
# results prior to re-id-ing: (4857, 23503)
# results prior to v10.5.5: (33, 20488)
# results with v10.5.5: (33, 6900)
```
## Results
The number of schema validation errors (eg "invalid_type") dropped from ~20,000 to ~7,000. 

## Samples
Here are some samples of the type of error that still remains
(err msgs are formatted as `f"{name} doc {doc['id']}: field {field} referenced doc {v} not of type {slot_range}"`)

- 'data_object_set doc nmdc:dobj-13-c1z03e41: field was_generated_by referenced doc nmdc:omprc-13-pwcfhd56 not of type Activity'
- 'library_preparation_set doc nmdc:libprp-11-wy2dc553: field has_input referenced doc nmdc:procsm-11-w0rz8234 not of type Biosample'
- 'metagenome_annotation_activity_set doc nmdc:wfmgan-11-ht6g9577.1: field part_of referenced doc nmdc:wfmgan-11-ht6g9577.1 not of type NamedThing'
- 'read_qc_analysis_activity_set doc nmdc:wfrqc-11-8rbb7473.1: field part_of referenced doc nmdc:wfrqc-11-8rbb7473.1 not of type NamedThing'
