### ISSUE TITLE
False positive type errors from alldocs ref integrity code

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#576]
We need to get to the bottom of what I believe are related issues. In both cases the range in linkml is specified with any_of but Jing's code, which i believe is using the schema.json, complains about a type error in https://github.com/microbiomedata/nmdc-runtime/issues/555

```py
'data_object_set doc nmdc:dobj-13-c1z03e41: field was_generated_by referenced doc nmdc:omprc-13-pwcfhd56 not of type Activity'
'library_preparation_set doc nmdc:libprp-11-wy2dc553: field has_input referenced doc nmdc:procsm-11-w0rz8234 not of type Biosample'
```

Note that the linkml documentation the global slot the definition appears to list range correctly
https://microbiomedata.github.io/nmdc-schema/was_generated_by/ but the induced linkml source is not correct https://microbiomedata.github.io/nmdc-schema/DataObject/

cc @turbomam @sierra-moxon @pkalita-lbl Would one of you please pair with Jing to get to the bottom of this?

There was some discussion over slack, unexplored, that the cause may be lack `inlined: true`

cc @shreddd

**Comment by pkalita-lbl** [comment]
@PeopleMakeCulture can you point me to the code that is producing the error messages quoted above and in #555?

**Comment by sierra-moxon** [comment]
I have a feeling that the same issue that Eric found and reported here: https://github.com/linkml/linkml/issues/2103 is what is causing the mismatch between the induced NMDC schema and the source NMDC schema (a fix is in the works on the LinkML side), but it would be good to see the code generating this error to make sure I'm not jumping to conclusions.

**Comment by aclum** [comment]
@PeopleMakeCulture were you able to provide the code?

**Comment by turbomam** [comment]
Should I be doing anything to help with this one?

**Comment by PeopleMakeCulture** [comment]
Sorry guys I had covid last week! I've added this to my queue for this week

**Comment by PeopleMakeCulture** [comment]
> I have a feeling that the same issue that Eric found and reported here: [linkml/linkml#2103](https://github.com/linkml/linkml/issues/2103) is what is causing the mismatch between the induced NMDC schema and the source NMDC schema (a fix is in the works on the LinkML side), but it would be good to see the code generating this error to make sure I'm not jumping to conclusions.

I agree that this is related to Eric's issue. 

@pkalita-lbl This is the notebook that I ran which generated the errors in #555 

Here's the relevant bit

```python3
# Iterate over each collection name
for name in sorted(collection_names):

    cls_name = collection_name_to_class_names[name][0]
    
    # NOTE: THIS IS WHAT'S INCORRECTLY INDUCING THE RANGE
    slot_map = {
        slot.name: slot
        for slot in nmdc_view.class_induced_slots(cls_name)
    }
    
    # Iterate over each document in this collection
    for doc in mdb[name].find():
        doc = dissoc(doc, "_id")

        # Iterate over each key/value pair in the document
        for field, value in doc.items():
            assert field in slot_map, f"{name} doc {doc['id']}: field {field} not a valid slot"
            slot_range = str(slot_map[field].range)
            assert slot_range, type(slot_range)
            if not slot_range in toplevel_classes:
                continue
            if not isinstance(value, list):
                value = [value]
            for v in value:
                if mdb.alldocs.find_one({"id": v}, ["_id"]) is None:
                    errors["not_found"].append(f"{name} doc {doc['id']}: field {field} referenced doc {v} not found")
                elif mdb.alldocs.find_one({"id": v, "type": slot_range}, ["_id"]) is None:
                    errors["invalid_type"].append(f"{name} doc {doc['id']}: field {field} referenced doc {v} not of type {slot_range}")
        
```

**Comment by ssarrafan** [comment]
Looks like it's in progress. Will move to the new sprint. Hope you feel better @PeopleMakeCulture .

**Comment by aclum** [comment]
Believed root cause for refscan issue is that was_generated_by range is not specified in berkeley schema.

**Comment by aclum** [comment]
@PeopleMakeCulture  did you figure out why the all docs implementation was having these errors? we can't use refscan until berkeley schema is rolled out so we need to get to the bottom of this.

**Comment by eecavanna** [comment]
Regarding debugging the issue, I added some "TODO" comments a while back to document the notebook author's rationale for having the notebook do certain things. I think that documentation will make it easier for people to help understand/debug the notebook. I will create a separate ticket about adding/filling in that documentation.

**Comment by shreddd** [comment]
In discussing with @PeopleMakeCulture this is related to the `any_of` issue for which @sierra-moxon is working on a [PR](https://github.com/microbiomedata/nmdc-runtime/issues/576) 

We can try to add some additional code to the notebook to workaround this until it is addressed upstream in LinkML. I'll let @PeopleMakeCulture and @eecavanna

**Comment by eecavanna** [comment]
During today's Referential Integrity squad meeting, I explained how refscan currently deals with `any_of`.

In short, if a slot has an `any_of` constraint, refscan will ignore the slot's `range` and will, instead, use the union of all ranges in the `any_of` constraint. For example, given `range = Foo`, `any_of[0].range = Bar`, and `any_of[1].range = Baz`, refscan will consider the slot's effective range to be the union of `Bar` (and all its subclasses) and `Baz` (and all its subclasses), disregarding the slot's `range`.

On the other hand, if a slot does not have an `any_of` constraint, refscan will use the slot's `range`. For example, given `range = Foo`, refscan will consider the slot's effective range to be `Foo` (and all its subclasses).

This is all implemented in a helper function called `get_names_of_classes_in_effective_range_of_slot` ([source](https://github.com/microbiomedata/refscan/blob/af092b0e068b671849fe0f323fac2ed54b81d574/refscan/lib/helpers.py#L141-L176)). That helper function is accompanied by a [unit test](https://github.com/microbiomedata/refscan/blob/af092b0e068b671849fe0f323fac2ed54b81d574/tests/test_helpers.py#L51-L78) and a contrived schema used by that [unit test](https://github.com/microbiomedata/refscan/blob/main/tests/schemas/schema_with_any_of.yaml).

**Comment by eecavanna** [comment]
Also during today's Referential Integrity squad meeting, I said I'm aware of **two distinct upstream issues** that could lead to erroneous referential integrity results, regardless of the referential integrity-checking algorithm. Those are:

1. The `was_generated_by` slot is not defined correctly in the Berkeley schema ([this PR](https://github.com/microbiomedata/berkeley-schema-fy24/pull/231)—not yet merged—contains a fix).
2. I don't know that the people who have used `any_of` to express their ideas—and the people that have implemented referential integrity checkers—and the people that implemented LinkML's `SchemaView` class—all share a common understanding of `any_of` (see previous two comments above).

**Comment by eecavanna** [comment]
Regarding item 2: As several squad members have suggested, one option for avoiding this issue is to refrain from using `any_of` in the schema and—instead—define some wrapper classes from which all of the classes currently specified via `any_of[].range` descend.

For example:

```diff
slots:
  pet:
-   any_of:
-     - range: Dog
-     - range: Cat
+   range: DomesticatedAnimal

classes:
  Dog:
+   is_a: DomesticatedAnimal
  Cat:
+   is_a: DomesticatedAnimal
+ # Here's a wrapper class.
+ DomesticatedAnimal:
```

> Caution: The above LinkML schema snippet was written by someone new to writing LinkML schemas (me).

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint.

**Comment by ssarrafan** [comment]
"At bat" so I will move to new sprint.

**Comment by ssarrafan** [comment]
@sierra-moxon Jing is gone for 2 weeks. Will you be working on this still or should I label this one backlog?

**Comment by ssarrafan** [comment]
Removing from sprint. No update, no response.

**Comment by eecavanna** [comment]
Hi @PeopleMakeCulture, looks like GitHub closed this issue when I merged the `berkeley` branch into the `main` branch a couple weeks ago. At the time, the `berkeley` branch included commit https://github.com/microbiomedata/nmdc-runtime/pull/695, which has the following message, which I think led to GitHub closing the associated issues.

![image](https://github.com/user-attachments/assets/c1e4401a-5a52-4da9-9cd9-893f3816f60e)

**Comment by PeopleMakeCulture** [comment]
See https://github.com/microbiomedata/nmdc-runtime/issues/696 for approach to consolidating notebook and dagster op approach to creating alldocs
