### ISSUE TITLE
`berkeley`: Validate or remove `_translate_omics_processing` function (in `gold_translator.py`) that returned an `nmdc.OmicsProcessing`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#586]
### Background

The presence of the `nmdc.OmicsProcessing` type hint was preventing the "Berkeley Runtime" from booting, so I [removed](https://github.com/microbiomedata/nmdc-runtime/commit/4fc23e55896eb72ea3797de29f941311800f7110) it as a quick fix for getting the "Berkeley Runtime" deployed (so that team members can "kick the tires" on the "Berkeley Runtime" and help us identify things that don't work they way they expect with the Berkeley schema; i.e. `nmdc-schema` versions 11+).

### Task

The task here is to validate that the `_translate_omics_processing` function still does what its author designed it to. Alternatively, the task here is to remove the function if it isn't necessary when the Runtime uses the Berkeley schema.

**Comment by aclum** [comment]
This should be fixed b/c gold translator code has been updated. @sujaypatil96  please confirm.
