### ISSUE TITLE
`berkeley`: Update activity related endpoints

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#593]
**Is your feature request related to a problem? Please describe.**
There are a number of endpoints for workflows with activity in the name, Activity doesn't exist as a class anymore in the berkeley schema, its been updated to PlannedProcess with WorkflowExecution being the child class that best maps to what was previously grouped under activities. The following endpoints should be renamed with descriptions and parameters also updated to remove references to activity
- [x] https://api-berkeley.microbiomedata.org/docs#/workflows/post_activity_workflows_activities_post suggested replacement endpoint name is `workflow_execution_post`
- [x] https://api-berkeley.microbiomedata.org/docs#/find/find_activities_activities_get suggested replacement endpoint name is `find_workflow_execution_get`
- [x] https://api-berkeley.microbiomedata.org/docs#/find/find_activity_by_id_activities__activity_id__get. suggested replacement endpoint name is `find_workflow_execution_by_id_get`

- [x] remove https://api-berkeley.microbiomedata.org/docs#/v1/post_activity_v1_workflows_activities_post, it has been deprecated for a while
- [x] remove https://api-berkeley.microbiomedata.org/docs#/workflow_execution_activities/post_activity_v1_workflows_activities_post, it has been deprecated for a while

**Describe the solution you'd like**
In the [berkeley branch ](https://github.com/microbiomedata/nmdc-runtime/tree/berkeley)of nmdc_runtime remove language about activities from endpoint names, descriptions, filters.

**Acceptance Criteria**
- grep with activit on nmdc-repo returns on matches for endpoint names and filter fields. Text coming from https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md will be updated separately after the endpoints themselves are updated.

Example scenario-based template:
Given I'm looking at [the swagger UI for the berkeley branch of nmdc-runtime](https://api-berkeley.microbiomedata.org/docs#/) , when I look a the endpoints, then there won't be any references to activity/activities.

**Describe alternatives you've considered**
Leave inconsistent and confusing endpoint names in place. 

cc @brynnz22 @mbthornton-lbl @picowatt @corilo @SamuelPurvine @shreddd

**Comment by aclum** [comment]
Eric suggested a endpoint redirect, or some return body that says the endpoint is deprecated, point to documentation.

**Comment by pkalita-lbl** [comment]
Suggestion in the July 25 infrastructure sync call was to have deprecated "activity" endpoints start returning an HTTP 410 response (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) along with a body that points the client to a documentation page explaining the new data model and new endpoints.

**Comment by aclum** [comment]
High priority for refactor rollout b/c of dependencies on workflows, notebooks, and API documentation.

**Comment by ssarrafan** [comment]
Moving to next sprint. @PeopleMakeCulture let me know if you're not planning to work this one. Thanks.

**Comment by eecavanna** [comment]
From today's metadata squad meeting: When this is done, workflow authors will start updating the workflows to use these new endpoint names.

**Comment by aclum** [comment]
@PeopleMakeCulture what is the status of this?

**Comment by PeopleMakeCulture** [comment]
> [@PeopleMakeCulture](https://github.com/PeopleMakeCulture) what is the status of this?

Should have an update merged by end of week!

**Comment by PeopleMakeCulture** [comment]
Merged #624
