### ISSUE TITLE
Add documentation to "Referential integrity checker (prototype)" notebook (alldocs-based)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#604]
The notebook [`docs/nb/bulk_validation_referential_integrity_check.ipynb`](https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/nb/bulk_validation_referential_integrity_check.ipynb) is coming up in conversation frequently (e.g. in https://github.com/microbiomedata/nmdc-runtime/issues/576) and at least one team member (me) has have found it difficult to discuss due to not understanding some of the things it does or the author's rationale for having the notebook do those things.

### Task

- [ ] Address the `TODO` comments in the notebook that pertain to documenting what it does/the author's rationale
- [ ] Run the result by a potential future contributor of the notebook to gauge the sufficiency of the docs

For example:

![image](https://github.com/user-attachments/assets/e1b3498e-722c-48d1-a52b-22e200438fc4)

![image](https://github.com/user-attachments/assets/7c1b3aef-6d38-4459-81e0-b9b627e6387f)

![image](https://github.com/user-attachments/assets/87fa50be-71f4-4060-b574-3440e22fe7af)

![image](https://github.com/user-attachments/assets/63cf9480-e78c-4235-ad86-e6d78ad0b9be)

![image](https://github.com/user-attachments/assets/a5c8c7d0-75c8-4b1b-8025-6c9ad5d267f3)

**Comment by ssarrafan** [comment]
Looks like there is aPR that may need to be reviewed before this is closed. Moving to new sprint.

**Comment by PeopleMakeCulture** [comment]
Thanks for opening a new ticket for this!

**Comment by PeopleMakeCulture** [comment]
@eecavanna Could you look at the updated comments and let us know if that answers your questions?
