### ISSUE TITLE
no longer have permission to generate site credentials

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#605]
**Describe the bug**
I used to with my personal login in runtime prod, have permissions to generate site credentials with the generate_credentials_for_site_client_sites__site_id__generateCredentials_post endpoint. I believe this is related to changes in how roles are modeled in runtime.

**To Reproduce**
1. log in as me
2. curl -X 'POST' \
  'https://api.microbiomedata.org/sites/cam-comp:generateCredentials' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer $TOKEN' \
  -d ''
3. response body of
`"detail": "You're not registered as an admin for this site"`
with a 403 response code

**Expected behavior**
response code of 200

**Screenshots**

**Acceptance Criteria**
- logged in as myself I am able to create client credentials.

**Comment by aclum** [comment]
Closing, this appears to work for site IDs im associated with but not for the site ID belonging to someone else.

**Comment by eecavanna** [comment]
I created a ticket about documentation this limitation in a way that shows the documentation on Swagger UI. Ticket: https://github.com/microbiomedata/nmdc-runtime/issues/606
