### ISSUE TITLE
changesheets:validate endpoint returning incorrect validation error

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-runtime#613]
**Description**
.Submitting the following .tsv file to the `changesheets:validate` endpoint returns an incorrect validation error 

Example changesheet:
```
id	action	attribute	value
nmdc:dobj-11-m2kj6723	update	file_size_bytes	1271907
nmdc:dobj-11-m2kj6723	update	md5_checksum	138c689c6067cf670dff71004688c98f
``` 
Note: file extension changes to .txt to be able to upload
[fragment.txt](https://github.com/user-attachments/files/16419830/fragment.txt)

**To Reproduce**
1. Go to api.microbiomedata.org
2. Authenticate with my name / PW
3. Scroll down metadata changesheets:validate / Click `Try it out` / Upload fragment.tsv / click Execute

Response Body:
```
{
  "detail": {
    "update_cmd": {
      "nmdc:dobj-11-m2kj6723": {
        "update": "data_object_set",
        "updates": [
          {
            "q": {
              "id": "nmdc:dobj-11-m2kj6723"
            },
            "u": {
              "$set": {
                "file_size_bytes": "1271907"
              }
            }
          },
          {
            "q": {
              "id": "nmdc:dobj-11-m2kj6723"
            },
            "u": {
              "$set": {
                "md5_checksum": "138c689c6067cf670dff71004688c98f"
              }
            }
          }
        ]
      }
    },
    "validation_errors": [
      [
        "'1271907' is not of type 'integer'"
      ]
    ]
  }
}
``` 

**Expected behavior**
The changesheet should validate

**Acceptance Criteria**
- file_size_bytes values are handled correctly
- changesheet should validate

**Comment by PeopleMakeCulture** [comment]
@mbthornton-lbl are you authenticating with the OAuth flow or with the (older) user name and password?

**Comment by bmeluch** [comment]
I think I am having a similar issue - some numbers in a changesheet are being read in as strings, and some are numbers. This is preventing the changesheet from validating.
`elev` is read as a number :white_check_mark:
`depth.has_raw_value` is read as a string :white_check_mark:
`depth.has_numeric_value` is also read as a string :x:

Is this the same issue? any advice? thank you!

<details>
<summary>TSV file snippet</summary>
<br>

```text
comment	action	id	attribute	value
add metadata to EMSL studies 50718 and 50267	update	nmdc:bsm-11-0pyv7738	depth.has_numeric_value	0.38
add metadata to EMSL studies 50718 and 50267	update	nmdc:bsm-11-0pyv7738	depth.has_raw_value	0.38 m
add metadata to EMSL studies 50718 and 50267	update	nmdc:bsm-11-0pyv7738	elev	719
add metadata to EMSL studies 50718 and 50267	update	nmdc:bsm-11-0pyv7738	depth.type	nmdc:QuantityValue
```

</details>

<details>
<summary>JSON response from api-dev changesheets:validate</summary>
<br>

```json
{
    "detail": {
        "update_cmd": {
            "nmdc:bsm-11-0pyv7738": {
                "update": "biosample_set",
                "updates": [
                    {
                        "q": {
                            "id": "nmdc:bsm-11-0pyv7738"
                        },
                        "u": {
                            "$set": {
                                "depth.has_numeric_value": "0.38"
                            }
                        }
                    },
                    {
                        "q": {
                            "id": "nmdc:bsm-11-0pyv7738"
                        },
                        "u": {
                            "$set": {
                                "depth.has_raw_value": "0.38 m"
                            }
                        }
                    },
                    {
                        "q": {
                            "id": "nmdc:bsm-11-0pyv7738"
                        },
                        "u": {
                            "$set": {
                                "elev": 719.0
                            }
                        }
                    },
                    {
                        "q": {
                            "id": "nmdc:bsm-11-0pyv7738"
                        },
                        "u": {
                            "$set": {
                                "depth.type": "nmdc:QuantityValue"
                            }
                        }
                    }
                ]
            }
        },
        "validation_errors": [
            [
                "'0.38' is not of type 'number'"
            ]
        ]
    }
}
```

</details>

**Comment by eecavanna** [comment]
I took a quick look and came away suspecting that the issue stems from [this "type coercion" code](https://github.com/microbiomedata/nmdc-runtime/blame/9ec7abb17d861a93a1f3064c2f891b14b55b52a5/nmdc_runtime/api/core/metadata.py#L205C55-L214), which seems to me to have been designed to coerce values originating in changesheets into Python's built-in data types, falling back to Python's `str` data type if it fails to do the former.

The schema says `elev` is of type `Float`; which I assume that code maps to Python's `float` data type. In contrast, the schema says `has_numeric_value` is of type `Decimal`; I suspect the code is not considering any of Python's built-in data types to be appropriate and, so, is falling back to `str`.

**Comment by turbomam** [comment]
I am always open to decreasing the number of non-integer numeric types we use in the schema, as long as we do a requirements analysis.

**Comment by PeopleMakeCulture** [comment]
From @eecavanna on [Slack](https://nmdc-group.slack.com/archives/C0739GREU9G/p1730417004366439?thread_ts=1722274214.695619&cid=C0739GREU9G):
> I took a quick look and came away suspecting that the issue stems from [this "type coercion" code](https://github.com/microbiomedata/nmdc-runtime/blame/9ec7abb17d861a93a1f3064c2f891b14b55b52a5/nmdc_runtime/api/core/metadata.py#L205C55-L214), which seems to me to have been designed to coerce values originating in changesheets into Python's built-in data types, falling back to Python's str data type if it fails to do the former.
The schema says elev is of type Float; which I assume that code maps to Python's float data type. In contrast, the schema says has_numeric_value is of type Decimal; I suspect the code is not considering any of Python's built-in data types to be appropriate and, so, is falling back to str.
I wonder whether the same issue would arise with any other slot whose type is Decimal.
