### ISSUE TITLE
`berkeley`: Replace `OmicsProcessing` with `DataGeneration` (in referential integrity checker notebook)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#629]
Notebook: https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/nb/bulk_validation_referential_integrity_check.ipynb

Details are in the comment linked below.

> OmicsProcessing should be DataGeneration.

_Originally posted by @aclum in https://github.com/microbiomedata/nmdc-runtime/pull/625#discussion_r1712211250_

**Comment by mslarae13** [comment]
@PeopleMakeCulture any sense of when this will be done? Not pressure! Just an estimated completion date

**Comment by mslarae13** [comment]
Wait! @PeopleMakeCulture at bat means ready, not in progress! Ha!
Do you also know when you'll start this? :)
