### ISSUE TITLE
`berkeley`: Replace `designated_class ` with `type` (in `ncbi_xml_utils.py` script)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#630]
Script: https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/site/export/ncbi_xml_utils.py

Details are in the comment linked below.

>  change `designated_class ` to `type`, `designated_class` doesn't exist in berkeley

_Originally posted by @aclum in https://github.com/microbiomedata/nmdc-runtime/pull/625#discussion_r1712214219_

**Comment by aclum** [comment]
@sujaypatil96 do you have time to work on this this sprint?

**Comment by aclum** [comment]
@sujaypatil96  Im adding this to next sprint. I commented in slack that we need alldocs in berkeley for this to work.

**Comment by aclum** [comment]
Does not block release of berkeley but would be nice to have done this sprint.

**Comment by sujaypatil96** [comment]
This should be part of a bigger ticket, the main task request of which should be the "migration" of the NCBI XML exporter to be compliant with the berkeley schema.

**Comment by aclum** [comment]
Feel free to update this ticket title or close in favor of a new ticket. This ticket was made based off tickets Eric made from PR review comments.

**Comment by ssarrafan** [comment]
@sujaypatil96 can this ticket be closed this sprint?

**Comment by sujaypatil96** [comment]
@ssarrafan no 🥲 we need to move this ticket to the next sprint.
