### ISSUE TITLE
`berkeley`: Synchronize Swagger UI documentation with standalone `api_gui.md` how-to guide

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#646]
We need to update the swagger UI documentation for berkeley to match the updates Brynn will make in nmdc documenation.

In runtime this is populated from in [main.py](https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/api/main.py)

updates should come from whatever branch gets used to address [this ticket](https://github.com/microbiomedata/NMDC_documentation/issues/65).

blocked on https://github.com/microbiomedata/NMDC_documentation/issues/65

Target sprint is Sept 9.

cc @PeopleMakeCulture @brynnz22

**Comment by mslarae13** [comment]
This is blocking https://github.com/microbiomedata/NMDC_documentation/issues/65

@aclum can you add what is needed to unblock this issue?

**Comment by aclum** [comment]
It is the other way around, this is blocked onhttps://github.com/microbiomedata/NMDC_documentation/issues/65,  at least the way we did it last time. Brynn wrote the documentation and then Jing copied it over.

**Comment by mslarae13** [comment]
Oh! ok!
So
Criteria to unblock:
- complete https://github.com/https://github.com/microbiomedata/NMDC_documentation/issues/65

**Comment by ssarrafan** [comment]
@aclum who should this be assigned to?

**Comment by aclum** [comment]
@eecavanna  or @PeopleMakeCulture. @PeopleMakeCulture  has three other berkeley tickets this sprint so whoever has more bandwidth once Brynn finishes her part(https://github.com/microbiomedata/NMDC_documentation/issues/65)

**Comment by eecavanna** [comment]
Progress on this ticket is no longer blocked; i.e. https://github.com/microbiomedata/NMDC_documentation/pull/70 is done (we are intentionally refraining from merging it into `main` because it describes the Berkeley Runtime, which is not in production yet).

**Comment by aclum** [comment]
@eecavanna were you going to take this or you'd prefer @PeopleMakeCulture work on it?

**Comment by eecavanna** [comment]
I'm planning to work on it today. I'll post an update here when I'm done working on it for the day, at which point I may also reassign the task to @PeopleMakeCulture alone. If there is work that remains this evening, I'd expect it to involve continuing a pattern I establish in the preceding commits (coming soon).

**Comment by eecavanna** [comment]
I'll be done with this tonight (er... before the sun rises in California). There are only 5 sections that changed in the how-go guide, and only 3 of them were present in the Swagger UI page; so there were only 3 blobs of text to copy/paste from one to the other.

**Comment by eecavanna** [comment]
I finished this. It's implemented in this PR: https://github.com/microbiomedata/nmdc-runtime/pull/682
