### ISSUE TITLE
`berkeley`: Change `workflow_execution`s endpoints to be `planned_process`

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-runtime#653]
**Is your feature request related to a problem? Please describe.**

The two endpoints `/workflow_executions` and `/workflow_executions/{workflow_execution_id}` replaced the old endpoints `/activities` and `/activities/activity_id`. The old endpoints allowed a user to query both the `WorkflowExecution` classes and the `PlannedProcess` classes. The new endpoints just allow us to query the `WorkflowExecution` classes. To retain the original functionality (so a user can also query, `MaterialProcessing` classes for example, can we change these endpoints to be called `planned_processes` and `planned_processes/{planned_process_id}`? And allow the endpoint to use any subclass of `PlannedProcess` according to the Berkeley schema: https://microbiomedata.github.io/berkeley-schema-fy24/PlannedProcess/

**Screenshots**

**Describe the solution you'd like**

Change the `/workflow_executions` and `/workflow_executions/{workflow_execution_id}` endpoints to be called `/planned_processes` and `/planned_processes/{planned_process_id}`? And allow the endpoints to use any subclass of `PlannedProcess` according to the Berkeley schema: https://microbiomedata.github.io/berkeley-schema-fy24/PlannedProcess/. 

Example user story template:
AS A NMDC API user,
[INSTEAD OF searching just workflow executions by the two workflow execution Find endpoints]
I WANT TO search any planned process IN https://microbiomedata.github.io/berkeley-schema-fy24/PlannedProcess/]
[SO THAT I can also retrieve MaterialProcessing records and DataGeneration records]

Example scenario-based template:
Given the broadening of the workflow execution endpoints to planned process endpoints, when I search for a planned process record, then I will be able to obtain other planned process records besides workflow execution records (like data generation and material processing records.

**Describe alternatives you've considered**
Leave the endpoints as they are after the workflow execution update and just lose the functionality of searching other types of records in the Find endpoints.

@aclum @PeopleMakeCulture @dwinston

**Comment by aclum** [comment]
cc @shreddd  ideally this sprint.

**Comment by eecavanna** [comment]
I'll take a look at this today to determine how comfortable I think I'd be taking ownership long term.

**Comment by ssarrafan** [comment]
> I'll take a look at this today to determine how comfortable I think I'd be taking ownership long term.

Thanks @eecavanna if you plan to work on this during this sprint can you chance the status to "to do" please, or if you're not can you remove it from this sprint till Jing is back.  

FYI @dwinston

**Comment by dwinston** [comment]
I'll take a stab at this today. Approach anticipated be to use `nmdc_schema.get_nmdc_view.ViewGetter.class_descendants`.

**Comment by eecavanna** [comment]
I think this will be done by the end of the "day" (calendar day) today. I'll move it to the next sprint if that doesn't happen.

**Comment by eecavanna** [comment]
This has been fixed (via PR https://github.com/microbiomedata/nmdc-runtime/pull/666).

**Comment by eecavanna** [comment]
Hi @brynnz22, the Berkeley Runtime now has a `GET /planned_processes` and `GET /planned_processes/{planned_process_id}` endpoint. Will you try them out and let me and/or @dwinston know whether the behavior is what you had in mind? (You can message us here, on Slack, etc.)
