### ISSUE TITLE
`berkeley`: Update `submission_portal_translator.py` for Berkeley rollout

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#655]
test_submission_portal_translator.py function test_get_dataset is failing in the berkeley branch
update submission_portal_translator.py and/or test data as needed to get this passing.

This PR overwrote the failure but we need to uncomment and fix this.
https://github.com/microbiomedata/nmdc-runtime/blob/a9cccfaa88e80adf634e9ba6763e503b6c193a65/tests/test_data/test_submission_portal_translator.py#L276

**Comment by aclum** [comment]
@sujaypatil96 @pkalita-lbl highest priority ETL to fix.

**Comment by aclum** [comment]
I believe updates other functions in test_submission_portal_translator.py, for example I would expect test_get_pi to assert type and it doesn't currently. So we have tests that are passing with pytest that i wouldn't consider valid with nmdc-schema 11.0.0rc20

**Comment by pkalita-lbl** [comment]
Fixed with https://github.com/microbiomedata/nmdc-runtime/pull/657. Not sure why the PR merge didn't close this issue.
