### ISSUE TITLE
API route: from `dataobject` id, return associated `biosample` ids

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-runtime#668]
**Is your feature request related to a problem? Please describe.**
The notebook squad is developing a notebook to query all NMDC data objects associated with NOM analyses and do a meta-analysis on them.  We start with data object ids and need to associate them with the biosamples from which they originate.  Although it is _possible_ with the current API calls, we have to make several calls and it still requires a fair amount of in depth knowledge of the schema.

**Describe the solution you'd like**
I would like an API call that where I can send a list of `dataobject` ids and it will return a list of `biosample` ids.  

Example user story template:
AS A user, IF I START WITH A LIST OF dataobjects, I have to traverse the `analysis_activity_set`, `omics_processing_set`, and maybe some `material_processing_set`s (like current extraction_set or pooling_set) to finally find the biosample ids and relevant biosample information (like is this sample from water or soil).  The user also needs to have very intimate knowledge of the schema to navigate this traversal.

**Acceptance Criteria**
- This should work with NEON data
- Can be given a list of 1000 data objects and return the biosample ids associated with them (pagination is fine).

**Additional context**
This is essentially a mirror API route from the request I've made here: https://github.com/microbiomedata/nmdc-runtime/issues/667

This is related to milestone https://github.com/microbiomedata/issues/issues/516 and https://github.com/microbiomedata/issues/issues/496

**Comment by PeopleMakeCulture** [comment]
Closing this ticket, post-decision to focus on broader associations endpoint (#717)
