### ISSUE TITLE
`berkeley` test_endpoints.py failures

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#675]
Need to update part_of to associated_studies  in test_endpoints.py

**Comment by eecavanna** [comment]
I think @aclum fixed this in commit https://github.com/microbiomedata/nmdc-runtime/pull/676/commits/226cb239835f53d8b47d99ea357b79023004c79c#diff-8a00b480f317f4c84a544c52103e784d2fb0a9d33d90d8cc7400bb05b84cb64eL298

**Comment by eecavanna** [comment]
Oops, I didn't notice the state of this ticket had already been changed to "In Review" and the PR was already linked to this ticket (to some extent). I'll close this ticket.
