### ISSUE TITLE
`berkeley`: Refrain from stopping tests at first failure (we want to see all failures)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#677]
**Describe the bug**
berkeley branch is stopping at the first failed test. I thought @PeopleMakeCulture  had updated the tests in the berkeley branch to run all of them, regardless of status but that is not what is currently happening so we can't see the full list of what tests are failing. This is needed to help distribute any remaining work for berkeley.

**To Reproduce**
In this PR https://github.com/microbiomedata/nmdc-runtime/pull/676 depending on which commit you look at a different test fails. Only one failures is happening at a time and then the tests stop.

**Expected behavior**
Tests should  not stop at the first failure so we can see all the failures.

cc @eecavanna @shreddd @pkalita-lbl 

Example user story template:
AS A {user|persona|system},
[INSTEAD OF {current condition}]
I EXPECTED {result}
[SO THAT {value or justification}]
[NO LATER THAN {best by date}]

**Screenshots**

**Acceptance Criteria**
- Clear to everyone involved
- Can be tested or verified 
- Either passes or fails (cannot be 50% completed, for example)
- Focus on the outcome, not how the outcome is achieved
- As specific as possible (fast page load speed vs. 3-second page load speed)
- if multiple criteria, present as a bulleted list of short scenarios (see template below)

Example scenario-based template:
Given (some given context or precondition), when (I take this action), then (this will be the specific outcome).

**Additional context**

**Comment by pkalita-lbl** [comment]
To be clear, this **is not** about running tests in parallel. This about the problematic use of the `-x` ([stop after first failure](https://docs.pytest.org/en/6.2.x/usage.html#stopping-after-the-first-or-n-failures)) argument [here](https://github.com/microbiomedata/nmdc-runtime/blob/c8a0477f0be744217b090cdd2db1f6d1e72145de/nmdc_runtime/test.Dockerfile#L43).

**Comment by aclum** [comment]
thanks @pkalita-lbl

**Comment by aclum** [comment]
@PeopleMakeCulture  i removed this in the branch im working on. We can discuss at the infra sync if we want to add this back in after berkeley is merged. @ssarrafan would you please add pytest behavior for runtime to the agenda.
