### ISSUE TITLE
`berkeley`: Fix failing tests in `test_gold_api_ops.py`

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#678]
see PR https://github.com/microbiomedata/nmdc-runtime/actions/runs/10912264692/job/30286578992?pr=676
FAILED tests/test_ops/test_gold_api_ops.py::test_gold_biosamples_by_study - d...
FAILED tests/test_ops/test_gold_api_ops.py::test_gold_projects_by_study - dag...
FAILED tests/test_ops/test_gold_api_ops.py::test_gold_analysis_projects_by_study
FAILED tests/test_ops/test_gold_api_ops.py::test_gold_study - dagster._core.e...

recommend opening a separate PR to fix these tests.
cc @pkalita-lbl @eecavanna

**Comment by eecavanna** [comment]
For the record, I `skip`-ed these tests in the `berkeley` branch, via commit 7a6cd98074e2350962b533696b13f20a6cefbf51 (part of PR https://github.com/microbiomedata/nmdc-runtime/pull/676/).
