### ISSUE TITLE
`berkeley`: Test `test_submit_workflow_activities` is being skipped and is incompatible with Berkeley schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#683]
test_submit_workflow_activities is being skipped by pytest, with comments about a race condition. Do you have more information and/or can the test be rewritten such that it doesn't have a race condition?

cc @eecavanna 

Other changes needed for berkeley compatiblity.
update `type` to `ReadQcAnalysis`
update `test_collection` to `workflow_execution_set`
update `id` to an nmdc-style identifier.

**Comment by eecavanna** [comment]
> update `id` to an nmdc-style identifier.

I think that's already the case. Here's a screenshot from the diff of PR #684, showing the `id`:

![image](https://github.com/user-attachments/assets/50f32dee-a0ea-40c0-a0cd-9146e7c0754c)

**Comment by aclum** [comment]
The linked PR fixes these.
