### ISSUE TITLE
`berkeley`: API endpoint `/data_objects/study/{study_id}` not returning correct results

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#689]
**Describe the bug**
This endpoint is returning an empty array b/c alldocs doesn't exist in berkeley

**To Reproduce**
1. curl -X 'GET' \
  'https://api-berkeley.microbiomedata.org/data_objects/study/nmdc%3Asty-11-33fbta56' \
  -H 'accept: application/json'
2. compare empty return body to results on production

**Expected behavior**
Response json body should contain the same records as production.

Example user story template:
AS A {user|persona|system},
[INSTEAD OF {current condition}]
I EXPECTED {result}
[SO THAT {value or justification}]
[NO LATER THAN {best by date}]

**Screenshots**

**Acceptance Criteria**
Response body  is ~51K in size. 

Example scenario-based template:
Given (some given context or precondition), when (I take this action), then (this will be the specific outcome).

**Additional context**
Consider adding test coverage for this endpoint.

cc @sujaypatil96 because ncbi export code also needs alldocs

**Comment by eecavanna** [comment]
Once https://github.com/microbiomedata/nmdc-runtime/pull/694 has been merged in, I expect this bug to also be squashed.

**Comment by eecavanna** [comment]
Now that #694 has been merged in, I'll open a PR having the above code change in it.

**Comment by ssarrafan** [comment]
@sujaypatil96 @eecavanna who needs to review this?

**Comment by eecavanna** [comment]
I merged it in without review (other than self-review) just now in the interest of time.

I would still like for @sujaypatil96 to review it when he gets a chance—and he can open a ticket (or message me on Slack) in case he has concerns about its contents. It is not urgent, from my perspective.

**Comment by eecavanna** [comment]
With the endpoint fix in place, and with the `alldocs` collection in place, the endpoint now returns a non-empty response:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/11c0dd10-d434-4e37-a8b0-e6cb235dd078">

The response (when downloaded as a file via Swagger UI) is 55 KB, which (in this context) I consider to be "in the ballpark" of the 51 KB @aclum put in the issue description. For example, maybe some workflows have added more data objects. 🤷 

<img width="349" alt="image" src="https://github.com/user-attachments/assets/7c5c2f45-c8ab-406c-924c-ef398540a6d7">

**Comment by aclum** [comment]
Confirmed fixed in berkeley
