### ISSUE TITLE
`berkeley`: GHA workflow on `berkeley` branch checks out wrong Git commit

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#700]
During the 2024.9 release (on Monday, September 23, 2024), @pkalita-lbl and I were trying to figure out why the GHA workflow (`python-app.yml`) that runs the unit tests was failing "on the tip of the `berkeley` branch" even though no relevant changes had been made on the `berkeley` branch since the workflow had last run successfully—the only changes that had been made were to a migration notebook, which does not affect the unit tests.

After digging in, @pkalita-lbl noticed that the GHA workflow was **checking out a different commit** than the one we had expected it to (we had expected it to check out the latest commit on the `berkeley` branch).

Here's a sequence of screenshots demonstrating this:

| Screenshot |
| -- |
| 1. Look at the Git commit hash of the latest commit on the `berkeley` branch. It's `9cb5850`. |
| <img src="https://github.com/user-attachments/assets/e1c556b8-fd0b-4a2c-8009-b0ec5d5c7824" width="800" /> |
| 2. Click the red "X" for the commit and click "Details" next to the failing check |
| <img src="https://github.com/user-attachments/assets/959cc845-c116-4836-8614-7b0d90552f18" width="800" /> |
| 3. Look at the Git commit hash in the "checkout" step. It's `aa26394`, as opposed to `9cb5850`. |
| <img src="https://github.com/user-attachments/assets/9df0dd49-95bd-4097-972f-e65574abcce1" width="800" /> |

This ticket represents the task of getting to the bottom of why the GHA workflow on the `berkeley` branch is checking out a commit that is not the one we expect it to.

**Comment by eecavanna** [comment]
GitHub shows commit `aa26394` here: https://github.com/microbiomedata/nmdc-runtime/commits/aa26394

**Comment by eecavanna** [comment]
According to GitHub (see second screenshot in the message above), the two parents of commit aa26394 are:
- 588287e (this is the latest commit on the `main` branch)
  ![image](https://github.com/user-attachments/assets/77ee3cd9-84d8-42a1-bc94-0c0b759fd721)
- 9cb5850 (this is the latest commit on the `berkeley` branch)
  ![image](https://github.com/user-attachments/assets/57605130-9ad1-4ca3-a096-1fb848b4a0a3)

So, the GHA workflow was checking out a commit — not on any branch — where the `berkeley` branch had been merged into the `main` branch. Interesting! That answers the question of _what_ it checked out.

Next steps:
- Find out _why_ it checked that out
- Prevent it from doing that in the future

**Comment by eecavanna** [comment]
>- Find out why it checked that out

I think I have a clue. I made an innocuous commit to the `berkeley` branch just now and then confirmed the GHA workflow was once again checking out a different commit. I noticed that the title on the GHA page was from a "DO NOT MERGE: ..." PR that I had created months ago, which stages the merge of `berkeley` into `main`. When I visited that PR page, I saw that it showed the recent commit undergoing GHA. When I clicked the orange bubble and looked at the commit being processed by GHA, I saw that different commit hash there.

![image](https://github.com/user-attachments/assets/3e90b168-6eb7-4e86-8293-60b3459962b9)

![image](https://github.com/user-attachments/assets/f600749f-4b34-47ef-b97f-4cb829552a4a)

So, I suspect the fact that I have a PR open where a merge from `berkeley` to `main` is being staged, is playing a role here. I may try closing that PR (it can always be re-opened or recreated) and seeing whether that has an effect on this symptom.

**Comment by ssarrafan** [comment]
@eecavanna what's the status of this?  Are you working on this now?  Will this be done this sprint?

**Comment by eecavanna** [comment]
This is unresolved and I do not expect to finish it this sprint. It can be moved to the next sprint. 

If it's still open when the `berkeley` branch has been merged into main, I'll close it as "moot."

**Comment by eecavanna** [comment]
I have deleted the `berkeley` branch (it was merged into `main` last week).

![Image](https://github.com/user-attachments/assets/c418507b-2cc9-4517-9b90-2fae87b00017)

Closing this issue as "moot."
