### ISSUE TITLE
`berkeley` test_endpoints.py failures in berkeley branch

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#703]
ERROR tests/test_api/test_endpoints.py::test_submit_workflow_activities - Typ...
ERROR tests/test_api/test_endpoints.py::test_find_data_objects_for_nonexistent_study
ERROR tests/test_api/test_endpoints.py::test_find_planned_processes - TypeErr...
ERROR tests/test_api/test_endpoints.py::test_find_planned_process_by_id - Typ...

I consider this a blocker for berkeley, these tests do not pertain to NEON ETL code so my expect ion is that these tests should pass.

@shreddd @dwinston 

@PeopleMakeCulture  and @eecavanna  please coordinate on who can look at this, this needs to be done this sprint.

**Comment by aclum** [comment]
Extra context: These tests were passing last week (https://github.com/microbiomedata/nmdc-runtime/actions/runs/10913769506/job/30290793194) but are now failing in 
[@Sujay Patil](https://nmdc-group.slack.com/team/U02UENGHECD)
 PR (https://github.com/microbiomedata/nmdc-runtime/actions/runs/11062170296/job/30736159983?pr=701), that PR is about ETL code so shouldnt impact the endpoints tests.
 
 Possibly related to issues with what commit github is using for the berkeley branch, see #700

**Comment by eecavanna** [comment]
I'm looking into this now. For reference, this is about the tests whose failures are represented by `E` in the pytest result summary.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/61e8e308-217a-4a9b-865e-a6ec588e58c3">

**Comment by eecavanna** [comment]
Fixed in #709
