### ISSUE TITLE
`berkeley`: Fortify test that targets function that generates `alldocs` collection

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#713]
The function that generates the `alldocs` collection is here:
https://github.com/microbiomedata/nmdc-runtime/blob/385982a19db1aa467494ef6d351f8fc6ca7bd608/nmdc_runtime/site/ops.py#L998

There is a test, here, that targets that function:
https://github.com/microbiomedata/nmdc-runtime/blob/385982a19db1aa467494ef6d351f8fc6ca7bd608/tests/test_ops/test_materialize_alldocs.py#L31

The task here is to ensure we consider the test to be an adequate test of the function; and, if not, make it so.

**Comment by eecavanna** [comment]
>ensure we consider the test to be an adequate test of the function

I do not consider it to be adequate, as it does not check anything _about_ the documents in the `alldocs` collection; e.g. what they `type` fields contain.

**Comment by eecavanna** [comment]
Hi @sujaypatil96, we talked about pairing on this. I'm going to draft a PR tonight, which I'll go over with you tomorrow or Friday.

**Comment by ssarrafan** [comment]
@sujaypatil96 @eecavanna if the pairing isn't done can you please add this to the next sprint.  Thanks!

**Comment by eecavanna** [comment]
This is implemented and awaiting review. If no review happens today, I will merge it in without review so it is included as part of next week's testing.

**Comment by eecavanna** [comment]
Done (merged into `berkeley` branch just now).
