### ISSUE TITLE
Add protections to main branch

### ISSUE THREAD

**Issue by elais** [microbiomedata/nmdc-runtime#72]
Now that the tests are running after the changes related to #64 #71 the next step would be to add protections to the main branch that require the tests to to pass before a pull request can be merged. 

If this is already done please close this issue but it will be good that this exists to document that the administrative changes have been made.

**Comment by dwinston** [comment]
@elais you should have admin privileges for this repo now, via membership in @microbiomedata/architecture-wg . Please go ahead and resolve this.

**Comment by elais** [comment]
I added the status check for merging to main and also changed the settings for the branch to require pull requests to merge.
