### ISSUE TITLE
Unable to update field that is a list using queries:run endpoint

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-runtime#736]
**Describe the bug**
Attached is a queries:update json for updating MetaProteomics records.  @aclum  and I are receiving a message that says "Input should be a valid dictionary or object to extract fields from", but we are failing to understand or see how this is formatted incorrectly.

**To Reproduce**
See attached queries:run.  It should update the nmdc:wfmp-11-1ky3j817.1 record.
[combined_queries_test_minimal.json](https://github.com/user-attachments/files/17440113/combined_queries_test_minimal.json)

**Comment by kheal** [comment]
This is blocking https://github.com/microbiomedata/issues/issues/897

**Comment by aclum** [comment]
Error code was 422 with  "msg": "Input should be a valid dictionary or object to extract fields from",

**Comment by kheal** [comment]
Thanks to @brynnz22  for helping troubleshoot this - the removal of the offending outer brackets fixed this.
