### ISSUE TITLE
Process Spruce NOM and GC-MS data

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-runtime#75]
This is the next step from[ issue 20](https://github.com/microbiomedata/nmdc-runtime/issues/20)
To process NOM and GC-MS data from the Spruce study

- [X] Processed NOM FT-ICR MS data

Data ingestion into MongoDB from EMSL using NMDC-runtime API:

- [x] Step 1: 

Create Biosample objects and biosample set
- BioSample Metadata (emsl:UUID)
- Parse data from  
[Spruce Sample and Dataset Excel File](https://docs.google.com/spreadsheets/d/1bppguaImZaGAlqqgJBVC9t6WwS7Pg0-3J1uIPj2Rxro/edit#gid=860381937)  

- [x] Step 2:

Create Omics Processing Objects and omics_processing_set  
- Parse data from  
[Spruce Sample and Dataset Excel File](https://docs.google.com/spreadsheets/d/1bppguaImZaGAlqqgJBVC9t6WwS7Pg0-3J1uIPj2Rxro/edit#gid=860381937)  
- This step create the map between Sample and Dataset ID

- [x] Step 3:

    
Create DataObject and data_object_sets for raw data 
- Parse data from  
 [Spruce Sample and Dataset Excel File](https://docs.google.com/spreadsheets/d/1bppguaImZaGAlqqgJBVC9t6WwS7Pg0-3J1uIPj2Rxro/edit#gid=860381937)  

- [x] Step 4:

Create DataObject and data_object_sets for data products 
- Parse data from  
[spruce_ftms_nom_data_products](https://nmdcdemo.emsl.pnnl.gov/nom/registration/spruce_ftms_nom_data_products.json )  

- [x] Step 5:

Create NomAnalysisActivity and nom_analysis_activity_set 
- Parse data from:  
[spruce_ftms_nom_metadata_products](https://nmdcdemo.emsl.pnnl.gov/nom/registration/spruce_ftms_nom_metadata_products.json)
        

- [x] Step 6:

Push data from EMSL using NMDC-Runtime

**Comment by ssarrafan** [comment]
@corilo please let me know if this should be in a different repo or assigned to someone else

**Comment by corilo** [comment]
@dehays @mslarae13 

NOM data has been processed for the Spruce Project. The data product and metadata registration files are available here: 

1) https://nmdcdemo.emsl.pnl.gov/nom/registration/spruce_ftms_nom_metadata_products.json

2) https://nmdcdemo.emsl.pnl.gov/nom/registration/spruce_ftms_nom_data_products.json

From the original 58 files, 8 did not passed the QC check and are not included. Only data listed on 1) should be ingested.

**Comment by ssarrafan** [comment]
@corilo are you expecting to complete processing the GCMS data this week?  Or do you think this needs to be moved to January?  Thanks.

**Comment by corilo** [comment]
> @corilo are you expecting to complete processing the GCMS data this week? Or do you think this needs to be moved to January? Thanks.

Hi Please move it to January, the task is dependable on getting the sample mapping to dataset Id from the metadata team.

**Comment by corilo** [comment]
Hey @David , @wdduncan.   Since we never done the ingestion using the API ourselves, can any of you show us how? We followed the tutorial, but them we are having issues validating that the data has been created, and we are now both (Yuri and @kfox1111) having issues with the credentials to push data to dev. Help please? This is the last task to close this issue!

**Comment by dehays** [comment]
@corilo @kfox1111   I'm assuming you are already familiar with the docs Donny created for this from your work on automation: [https://microbiomedata.github.io/nmdc-runtime/tutorial-metadata-in/](https://microbiomedata.github.io/nmdc-runtime/tutorial-metadata-in/)

It is unclear to me whether you have the necessary site client credentials setup.  It sounds like you are trying to use individual API account / psw pairs when you authenticate.

I will investigate whether I have privs to create site credentials (It's also documented there.)

And we can arrange a time to step through adding your metadata together; perhaps including Sam and Anub as they will need to be able to do this as well.

**Comment by kfox1111** [comment]
I've got a service account for uploading data, and that is working, and a personal account and the password I have for that no longer works. I was trying to use the personal account to verify the data made it in. The service account doesn't seem to have enough permissions to do so.

**Comment by dwinston** [comment]
@kfox1111 are you still blocked on this?

**Comment by kfox1111** [comment]
We were able to upload some data and manually verify it was uploaded. My personal account is still locked out (I think @corilo can help me fix that now). I still need to figure out a programmatic way to know if the upload fully succeeded or not.

**Comment by dwinston** [comment]
@kfox1111 will the [`/nmdcschema/{collection_name}`](https://api.dev.microbiomedata.org/docs#/metadata/list_from_collection_nmdcschema__collection_name__get) or `/nmdcschema/{collection_name}/{doc_id}` API routes help you programmatically verify the upload? This would be after the upload is successfully validated. The `/objects/` route family should help you confirm that the uploaded bytes are accessible, assuming you saved the object ID on upload (you can also use GET /objects with a mongodb-style filter if you don't know the object ID but know other attributes).

**Comment by kfox1111** [comment]
Trying to use the /objects api right now. Filtering isn't working how I would expect:
{"size": {"%gt": 0}}  should give me something?

I'll have a look at the /nmdcschedma api. Thanks.

**Comment by kfox1111** [comment]
I was able to get some data via /nmdcschema/{collection_name}
collection_name: omics_processing_set
filter: {"id": "emsl:570991"}

So I can now see if the data makes it all the way in. I need to identify some terminal states to know when it will never make it in.

Also, is the metadata in process atomic? Will it ever partially ingest data or is it all or nothing?

**Comment by kfox1111** [comment]
Ok. I think I got it figured out:
```
{
  "resources": [
    {
      "id": "nmdc:sys0x20z8x82",
      "done": true,
      "expire_time": "2022-02-13T22:48:43.997000",
      "result": {
        "omics_processing_set": {
          "writeErrors": [],
          "writeConcernErrors": [],
          "nInserted": 0,
          "nUpserted": 0,
          "nMatched": 50,
          "nModified": 50,
          "nRemoved": 0
        }
      },
      "metadata": {
        "done_at": "2022-01-14T22:49:00+00:00",
        "model": "nmdc_runtime.api.models.job.JobOperationMetadata",
        "job": {
          "workflow": {
            "name": null,
            "description": null,
            "capability_ids": null,
            "id": "metadata-in-1.0.0",
            "created_at": null
          },
          "name": null,
          "description": null,
          "id": "nmdc:sys05c7pf815",
          "created_at": null,
          "config": {
            "object_id": "sys0ptw4ja32"
          },
          "claims": []
        },
        "site_id": "nmdc-runtime"
      }
    }
  ],
  "next_page_token": null
}
```

**Comment by dwinston** [comment]
> Also, is the metadata in process atomic? Will it ever partially ingest data or is it all or nothing?

@kfox1111 it is atomic at the collection level. So, for example, if you were submitting new biosample docs and new study docs as part of the same metadata-in job, it is possible that e.g. the biosample docs would get in and not the study docs. Note, however, that both collections would need to pass validation first. There is currently no retry logic for this scenario, but it does get logged.

**Comment by Lebedeva-Sonya** [comment]
Hi! 

I’m still listed on this task :)

Yours sincerely 
Sofya Lebedeva

**Comment by corilo** [comment]
@ssarrafan, @dehays  All Spruce NOM data have been successfully added to dev, and I'm assuming that no modification to the code or data is needed to move to data production. The GC-MS data were not included because the samples were pore water, as discussed with @mslarae13
