### ISSUE TITLE
Swagger UI shows "😱 Could not render response" when sending request to newly-updated Runtime instance

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-runtime#775]
**Describe the bug**
Different behavior in swagger with  list_from_collection_nmdcschema__collection_name__get end point between dev and prod. Note using curl produces the same results.
Response is '😱 Could not render responses_Responses, see the console.'

**To Reproduce**
search by collection name of workflow_execution_set and a filter of {"id":"nmdc:wfmb-13-1v78b457.1"} on https://api-dev.microbiomedata.org/docs#/metadata/list_from_collection_nmdcschema__collection_name__get 

**Expected behavior**
200 with a response json which can be downloaded, see runtime prod behavior on this same endpoint.

Example user story template:
AS A {user|persona|system},
[INSTEAD OF {current condition}]
I EXPECTED {result}
[SO THAT {value or justification}]
[NO LATER THAN {best by date}]

**Screenshots**
<img width="1596" alt="Screenshot 2024-11-14 at 2 54 36 PM" src="https://github.com/user-attachments/assets/9139637f-1fb3-4c2e-9bb7-0962060d6494">

**Acceptance Criteria**
Above query results in a 200 response code when executed in dev using the swagger UI.

**Comment by eecavanna** [comment]
It's working OK for me (i.e. I haven't been able to reproduce this).

![image](https://github.com/user-attachments/assets/cf8edbbc-1569-471f-9a1c-b72d231d6680)

Will you refresh the page in your web browser and try again?

**Comment by eecavanna** [comment]
I am wondering whether you have had the web page open for a few days, in which case, it might have been served up by the _old_ version of the Runtime; but now is trying to interact with the _new_ version of the Runtime.

**Comment by eecavanna** [comment]
> Note using curl produces the same results.

hmm... if `curl` is also showing the error (I take it that's what you meany by "same results"), then a stale web page is not the issue (at least is not the _only_ issue).

**Comment by eecavanna** [comment]
That error message looks to me like a Swagger UI error message; in which case, the "console" it's referring to is the web browser's JavaScript console.

**Comment by eecavanna** [comment]
I think I may have misinterpreted what you meant by "same results." Does `curl` produce the error for you also, or does `curl` fetch the results normally (i.e. with no error)? I'm talking about the development Runtime API, not the production one.
