### ISSUE TITLE
add unit tests for new notebook

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-runtime#79]
Add unit tests for new notebook operations (e.g., remove item, add item).

**Comment by dwinston** [comment]
@wdduncan status? Is there a WIP PR to connect this to?

**Comment by wdduncan** [comment]
@dwinston I have not had time to start a PR for this.

**Comment by dwinston** [comment]
Okay. No problem. I just wanted to know the latest status. Thank you.

**Comment by wdduncan** [comment]
@dwinston I'm re-assigning this to @sujaypatil96. He may want to assign someone else.

**Comment by dwinston** [comment]
Stale / no longer relevant.
