### ISSUE TITLE
Schedule cron job in dagster to materialize alldocs daily

### ISSUE THREAD

**Issue by PeopleMakeCulture** [microbiomedata/nmdc-runtime#809]

**Comment by dwinston** [comment]
@PeopleMakeCulture can we use [MongoDB change streams](https://www.mongodb.com/docs/v6.0/changeStreams/) to implement an event sourcing strategy for immediate and incremental reconciliation of `alldocs` with the upstream (normalized) schema collections? This might not be too tricky, and would result in a (substantially) less-stale-less-often `alldocs` collection.

Related to #696 and #717.

**Comment by eecavanna** [comment]
Maybe related: https://github.com/microbiomedata/nmdc-runtime/pull/810
