### ISSUE TITLE
Documentation file `howto-guides/claim-and-run-jobs.md` contains a broken link

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#820]
**Describe the bug**

From the Mkdocs build output:

```
WARNING -  Doc file 'howto-guides/claim-and-run-jobs.md' contains a link 'guide-create-triggers.md', but the target 'howto-guides/guide-create-triggers.md' is not found among documentation files.
```

**To Reproduce**

1. Go to https://microbiomedata.github.io/nmdc-runtime/howto-guides/claim-and-run-jobs/
2. Click on the link that says "Guide - Create Workflow Triggers To Spawn Jobs"
3. See error page

**Expected behavior**

User story:

AS A user,
INSTEAD OF seeing at an error page when I clicked the link,
I EXPECTED to see a page about creating triggers

**Screenshots**

Here's the broken link:

![image](https://github.com/user-attachments/assets/7ea184cf-b25c-4d84-937f-12538170c2ef)

Here's the error page it leads to:

![image](https://github.com/user-attachments/assets/3ad723ff-e495-4f5d-bbca-396b4faa92a0)

**Comment by Brijeshthummar02** [comment]
@eecavanna can you show me the path to file where it should be changed and also correct link for it, thanks.

**Comment by eecavanna** [comment]
Hi @Brijeshthummar02,

> can you show me the path to file where it should be changed

A relative path to the Markdown file containing the broken link is listed in the first part of the warning message above:

```
WARNING -  Doc file 'howto-guides/claim-and-run-jobs.md' contains [...]
```

That path is relative to the following base directory in this repository:

```
docs/
```

So, the full path to that file in this repository is:

https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/howto-guides/claim-and-run-jobs.md

> and also correct link for it

I assume the author intended for the link to point here:

https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/howto-guides/create-triggers.md

Looks like there is an extra `guide-` in the URL currently in use in the Markdown file, per the warning message above:

> [...] a link 'guide-create-triggers.md'

**Comment by Brijeshthummar02** [comment]
@eecavanna pr #823 according to me will point to perfect file.
