### ISSUE TITLE
Documentation file `howto-guides/jobs/gold-translation-etl.md` contains a broken link 

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#821]
**Describe the bug**

From the Mkdocs build output:

```
WARNING -  Doc file 'howto-guides/jobs/gold-translation-etl.md' contains a link '../tutorials/tutorial-metadata-in.md', but the target 'howto-guides/tutorials/tutorial-metadata-in.md' is not found among documentation files.
```

**To Reproduce**

1. Go to https://microbiomedata.github.io/nmdc-runtime/howto-guides/jobs/gold-translation-etl/
2. Click on the link that says "submit this metadata as JSON through the API"
3. See error page

**Expected behavior**

User story:

AS A user,
INSTEAD OF seeing at an error page when I clicked the link,
I EXPECTED to see a page about submitting metadata to the API

**Screenshots**

Here's the broken link:

![image](https://github.com/user-attachments/assets/44a39b05-54c1-485b-a974-b87454a95a8b)

Here's the error page it leads to:

![image](https://github.com/user-attachments/assets/865bb41d-d3f3-4e53-bf0e-c835b2284d89)

**Comment by Brijeshthummar02** [comment]
@eecavanna can you show me the path to file where it should be changed and also correct link for it, thanks.

**Comment by eecavanna** [comment]
Hi @Brijeshthummar02,

> can you show me the path to file where it should be changed

A relative path to the Markdown file containing the broken link is listed in the first part of the warning message above:

```
WARNING -  Doc file 'howto-guides/jobs/gold-translation-etl.md' [...]
```

That path is relative to the following base directory in this repository:

```
docs/
```

So, the full path to that file in this repository is:

https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/howto-guides/jobs/gold-translation-etl.md

> and also correct link for it

I assume the author intended for the link to point here:

https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/tutorials/metadata-in.md

Looks like there is an extra `tutorial-` in the URL currently in use in the Markdown file, per the warning message above:

> [...] contains a link '../tutorials/tutorial-metadata-in.md'

**Comment by Brijeshthummar02** [comment]
@eecavanna #824 will resolve broken link.
