### ISSUE TITLE
Implement API endpoint that performs multiple workflow-related operations

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-runtime#839]
In response to me talking about adding a referential integrity check (WIP [here](https://github.com/microbiomedata/nmdc-runtime/pull/835)) to the `/metadata/json:validate` endpoint, @aclum pointed out that there is a workflow automation script that currently does the following:
1. Uses the `/queries:run` API endpoint to update a document's `has_output` list
2. Uses the `/metadata/json:submit` API endpoint to create `data_object_set` documents

Between the first and second of those operations, the database will have a broken reference(s) in it; i.e. the `has_output` list will contain the `id` value of a document that does not exist in the database yet. Note: This is my understanding of the situation based upon Slack messages.

At this point, I am creating this ticket to learn more about the specific API requests involved in this sequence of requests. My goal with this discovery process is to make a concrete plan for implementing a single API endpoint that the workflow automation script can use to perform the database operations it needs to perform, without leaving the database in a state where it lacks referential integrity.

**Comment by eecavanna** [comment]
Hi @mbthornton-lbl and @aclum, will you point me to the code in the https://github.com/microbiomedata/nmdc_automation/ repo that performs that sequence of requests?

I looked at the [run_import.py](https://github.com/microbiomedata/nmdc_automation/blob/main/nmdc_automation/run_process/run_import.py) script today and concluded that it only makes requests to `/metadata/json:submit` and `/workflows/workflow_executions`. I didn't see any requests being made to `/queries:run`.

In general, I'm trying to identify the requirements for the single API endpoint (e.g. accept an A, B, and C as HTTP request parameters, update an X in the database, create a Y in the database, and return a Z in the HTTP response).

**Comment by eecavanna** [comment]
Oops... I mixed up the URLs in my previous comment. I have fixed them there and will now delete _this_ follow-up comment.

**Comment by dwinston** [comment]
@eecavanna @shreddd was it decided during the infra sync (tens of) minutes ago that this issue can be closed? I'd be fine with that.

**Comment by eecavanna** [comment]
Yes. Several people, including one of the original stakeholders here, indicated that they would prefer this be handled at the client; i.e. by changing the order of operations so that the to-be-referenced thing gets created before the reference-er gets updated to reference it.

We can reopen this if their stance changes as those client-side changes take shape.
