### ISSUE TITLE
Adding multiple credit associations to a study via change sheet no longer works.

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-runtime#87]
Bill  you added the applied_roles attribute that takes a list of values (that must match the credit enum in nmdc.yaml).

I have applied the changesheets from [January Change Sheets](https://drive.google.com/drive/folders/1_n6ZjK3z2jb535V1n5jTf9Myuh0jvk79)

First, removing the existing has_credit_associations attribute from each of 7 studies.  Then applying 7 change sheets to add credit associations to the has_credit_associations list setting the applied_roles to the list of string values from the credit enum.

Change sheet validation and submission are both successful.  The DAGster apply_changesheet jobs are all successful.

However, the study documents in Mongo only have a single credit_association in their has_credit_associations list:

```
`{
    "id": "gold:Gs0135149",
    "name": "Bulk soil microbial communities from the East River watershed ...",
    
    ...
    
    "has_credit_associations": [{
        "applied_roles": ["Investigation", "Formal Analysis", "Writing review and editing"],
        "applies_to_person": {
            "name": "Malak Tfaily",
            "email": "tfaily@arizona.edu",
            "orcid": "orcid:0000-0002-3036-2833"
        }
    }]
}`
```

Compare that with the change sheet [Brodie add roles changesheet](https://docs.google.com/spreadsheets/d/1uitChu27bWMU5oOKx16cr0WEX9G02V64Pt-s36frdnU) where Malak is neither the first or the last person for which a credit association object is being created.

**Comment by dehays** [comment]
Per conversation with Bill.  Changed operator from 'update' to 'insert items' for has_credit_associations.  But problem behavior remains.

Example changesheet here: [Brodie credit roles](https://docs.google.com/spreadsheets/d/1uitChu27bWMU5oOKx16cr0WEX9G02V64Pt-s36frdnU)

**Comment by wdduncan** [comment]
This has been fixed.
