### ISSUE TITLE
Change sheets to modify EMSL ID biosamples cannot determine document set

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-runtime#88]
This comes up with the change sheet to add 5 GOLD environment attributes to 17 SPRUCE samples that were used at EMSL but never at JGI (and therefore have no corresponding GOLD biosample record).

Aside - these biosamples are also missing part_of attributes.  So the change sheet was adding those.  Was surprised that part_of is not required on biosample.  Seems samples should always be associated with their study.

Change sheet - [Add GOLD env terms to EMSL only SPRUCE biosamples](https://docs.google.com/spreadsheets/d/1RCIk04o26xgZ0_Vkk76vfjaSsABpJinM4uVHaB3Glus)

Error response from changesheet validation:

`{
  "detail": "('Cannot determine the type of class for ', 'emsl:2f7107d6-5dd1-11ec-bf63-0242ac130002')"
}`

I think there is a failing attempt to infer the Mongo document collection (class) from the ID.  Perhaps the changesheet should just include a column for the Mongo collection rather than being clever and trying to figure it out.

**Comment by wdduncan** [comment]
@dehays looking at the biosample record:
![image](https://user-images.githubusercontent.com/3186638/150850094-40b8a057-5b64-4cc4-a3bb-07bca1189048.png)

Can you add a `type` value to the biosample? I.e.: 
```
type: nmdc:Biosample
```

**Comment by dehays** [comment]
I added type to the 17 biosample records and re ran the change sheet to add the part_of and GOLD env terms.  I see that Mongo was updated as I expected.  Closing.

Bill will make type a required attribute.  Change sheet processing relies on type to determine the Mongo collection by ID.
