### ISSUE TITLE
users/sites -> agents

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-runtime#95]
It has been confusing to have two disjoint types of authenticated entities, i.e. users and site clients, and to know which one needs to be selected for a given protected endpoint. All being agents, with user-id and password supplied via HTTP Basic Auth, will hopefully simplify the situation.

Refactor “users” and “site clients” stuff to just “agents”. An agent may be a prov:Person. An agent may also be a software agent prov:SoftwareAgent, working on behalf of a prov:Person. Let agent.type be a prov:Agent, i.e. a prov:Person, a prov:Organization, or a prov:SoftwareAgent.

Furthermore, a prov:Person agent may act on behalf of a prov:Organization.

So, forget Sites. There are prov:Organization and prov:Person entities that can participate in job runs.

And forget Users and Site Clients. There are only prov:Agent entities that supply {user_id,password} HTTP Basic Auth credentials.

A prov:Person entity :p may spawn a prov:SoftwareAgent entity :sa to act on its behalf, i.e :sa prov:actedOnBehalfOf :p.

**Comment by dwinston** [comment]
![runtime-api-agents](https://user-images.githubusercontent.com/1497854/152036542-166b2245-a23f-485b-a39f-53d755280c00.png)

**Comment by kfox1111** [comment]
no jwt tokens ever or just not for initial authentication to get a jwt? There's a big advantage IMO to having one spot for auth rather then at every endpoint.

**Comment by kfox1111** [comment]
Might want to consider something like Keycloak as well. we use it regularly and has a bunch of features that may simplify this. Feels like this may be reinventing some wheels.

**Comment by dwinston** [comment]
> There's a big advantage IMO to having one spot for auth rather then at every endpoint.

@kfox1111 I'm not sure how you're distinguishing jwt tokens from http basic auth here.

With jwt tokens, every request to every endpoint that needs authorization needs a header like
```
Authorization: Bearer <supplied_value>
```

With http basic auth, every request to every endpoint that needs authorization needs a header like
```
Authorization: Basic <supplied_value>
```

so in practice, the only difference is that jwt tokens are intended to be short-lived, whereas basic auth credentials are not. I think that in our case, user agents are long-lived. Folks will either use their browser, their laptop, or run scripts under a user/collab account on a shared computing system.

**Comment by kfox1111** [comment]
Not quite. With Basic, each service would have to handle validating the password, as well as some authz stuff, especially the features around delegation of permissions to a service acting on the users behalf. oauth2/oidc centralizes that stuff into a hardened security related server that deals with all that and you can then have all your api just validate the token is from the trusted server along with any additional authz you want to happen at the api endpoints. I'd be happy to have  quick call with you and show you some of the stuff we have running here if it would help.

**Comment by dwinston** [comment]
Oh sure, I guess by "in practice" I meant "in _our_ practice", i.e. for the NMDC pilot we just have one central service that can include auth(z) as part of its service offering. delegation of perms in our case looks like a person creating a software agent (with its own userid/pass) to act on the person's behalf. I do understand the value of jwts in a more distributed service scenario.

**Comment by kfox1111** [comment]
If all you have now, or plan to have soon, is a monolithic code base where you can just front it all with the same decorator for doing auth, then yes, that would probably be easiest.

It also requires clients to either be trusted or the user to go through the process of creating the service credentials and passing those along.
---

oauth2/oidc is a bit more then just jwt. Its also a process for a user to prove to the identity provider who they are, then hand a token over to a client so the client can act on their behalf. the client can then potentially even get fresh tokens itself to talk to the backend services when the user isn't even involved. The token usually given in this case is often a jwt though. So does fit in the existing model.

It allows a user to logout of a client while the client can still be usable by other users. Tokens expire in well defined intervals. The identity provider can pass additional data to the backend services via claims in the jwt. The IDP can also restrict which backend services a client/token can be used with. so not only delegation but restricted delegation.

This model does stuff like allow 3rd party applications to safely be able to integrate with your services. Basically the same way 3rd party things can integrate with google services. They use oauth2/oidc as well. So does facebook, github, etc etc. Its basically become the standardized way of doing this sort of thing.

I think part of it is, its already kind of distributed, when you consider the clients talking to the nmdc services are actually part of the overall system. Just 3rd party components. and having controls around those is useful too. A lot of this comes for minimal cost by using an existing solution rather then coding something new.

**Comment by dwinston** [comment]
I agree with all that.

> If all you have now, or plan to have soon, is a monolithic code base where you can just front it all with the same decorator for doing auth, then yes, that would probably be easiest.

This is exactly our situation. The current codebase serves as an oauth2 provider of jwts for its own services. Rather than using the oauth2/jwt standard (https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/) and having users worry about two-step requests (get a token, provide the token) and token expiration, I think it'd be simpler to switch to the http basic auth standard (https://fastapi.tiangolo.com/advanced/security/http-basic-auth/). I definitely have no interest in coding something new. :)

**Comment by kfox1111** [comment]
I guess part of the question is, are you going to be tracking who uploads what? I'd really rather not all the data coming from pnnl to be owned by me.

**Comment by kfox1111** [comment]
wow. yeah. that python lib makes you keep track of a lot of stuff yourself. Something like Keycloak takes care of a lot of it, itself.

**Comment by dwinston** [comment]
The provenance would be recorded, e.g. which agent posted the data, but this would not be equated with ownership. Just like a user now may e.g. manage the pnnl site, an agent could act on behalf of the pnnl org.

**Comment by dwinston** [comment]
superceded by, and useful as reference discussion for, #310.
